<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="20544.3"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_0_24" index="23" value="1.00000"/>
  <variable name="x_0_25" index="24" value="1.00000"/>
  <variable name="x_0_26" index="25" value="1.00000"/>
  <variable name="x_0_27" index="26" value="1.00000"/>
  <variable name="x_1_0" index="27" value="1.00000"/>
  <variable name="x_2_8" index="61" value="1.00000"/>
  <variable name="x_3_0" index="81" value="1.00000"/>
  <variable name="x_4_0" index="108" value="1.00000"/>
  <variable name="x_5_3" index="138" value="1.00000"/>
  <variable name="x_6_13" index="174" value="1.00000"/>
  <variable name="x_7_0" index="189" value="1.00000"/>
  <variable name="x_8_0" index="216" value="1.00000"/>
  <variable name="x_9_0" index="243" value="1.00000"/>
  <variable name="x_10_5" index="275" value="1.00000"/>
  <variable name="x_11_9" index="306" value="1.00000"/>
  <variable name="x_12_1" index="325" value="1.00000"/>
  <variable name="x_13_0" index="351" value="1.00000"/>
  <variable name="x_14_23" index="400" value="1.00000"/>
  <variable name="x_15_0" index="405" value="1.00000"/>
  <variable name="x_16_7" index="439" value="1.00000"/>
  <variable name="x_17_21" index="479" value="1.00000"/>
  <variable name="x_18_19" index="504" value="1.00000"/>
  <variable name="x_19_0" index="513" value="1.00000"/>
  <variable name="x_20_0" index="540" value="1.00000"/>
  <variable name="x_21_11" index="578" value="1.00000"/>
  <variable name="x_22_0" index="594" value="1.00000"/>
  <variable name="x_23_0" index="621" value="1.00000"/>
  <variable name="x_24_0" index="648" value="1.00000"/>
  <variable name="x_25_15" index="690" value="1.00000"/>
  <variable name="x_26_22" index="724" value="1.00000"/>
  <variable name="x_27_12" index="741" value="1.00000"/>
  <variable name="u_1" index="756" value="30.00000"/>
  <variable name="u_2" index="757" value="28.00000"/>
  <variable name="u_3" index="758" value="30.00000"/>
  <variable name="u_4" index="759" value="30.00000"/>
  <variable name="u_5" index="760" value="27.00000"/>
  <variable name="u_6" index="761" value="15.00000"/>
  <variable name="u_7" index="762" value="30.00000"/>
  <variable name="u_8" index="763" value="30.00000"/>
  <variable name="u_9" index="764" value="30.00000"/>
  <variable name="u_10" index="765" value="11.00000"/>
  <variable name="u_11" index="766" value="28.00000"/>
  <variable name="u_12" index="767" value="16.00000"/>
  <variable name="u_13" index="768" value="25.00000"/>
  <variable name="u_14" index="769" value="6.00000"/>
  <variable name="u_15" index="770" value="28.00000"/>
  <variable name="u_16" index="771" value="8.00000"/>
  <variable name="u_17" index="772" value="8.00000"/>
  <variable name="u_18" index="773" value="11.00000"/>
  <variable name="u_19" index="774" value="30.00000"/>
  <variable name="u_20" index="775" value="30.00000"/>
  <variable name="u_21" index="776" value="25.00000"/>
  <variable name="u_22" index="777" value="30.00000"/>
  <variable name="u_23" index="778" value="30.00000"/>
  <variable name="u_24" index="779" value="29.00000"/>
  <variable name="u_25" index="780" value="18.00000"/>
  <variable name="u_26" index="781" value="8.00000"/>
  <variable name="u_27" index="782" value="8.00000"/>
 </variables>
</CPLEXSolution>
