<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="20109.2"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_0_21" index="20" value="1.00000"/>
  <variable name="x_0_24" index="23" value="1.00000"/>
  <variable name="x_0_25" index="24" value="1.00000"/>
  <variable name="x_0_26" index="25" value="1.00000"/>
  <variable name="x_1_14" index="41" value="1.00000"/>
  <variable name="x_2_27" index="82" value="1.00000"/>
  <variable name="x_3_0" index="84" value="1.00000"/>
  <variable name="x_4_16" index="127" value="1.00000"/>
  <variable name="x_5_11" index="150" value="1.00000"/>
  <variable name="x_6_22" index="189" value="1.00000"/>
  <variable name="x_7_18" index="213" value="1.00000"/>
  <variable name="x_8_17" index="240" value="1.00000"/>
  <variable name="x_9_0" index="252" value="1.00000"/>
  <variable name="x_10_0" index="280" value="1.00000"/>
  <variable name="x_11_4" index="312" value="1.00000"/>
  <variable name="x_12_0" index="336" value="1.00000"/>
  <variable name="x_13_23" index="386" value="1.00000"/>
  <variable name="x_14_0" index="392" value="1.00000"/>
  <variable name="x_15_0" index="420" value="1.00000"/>
  <variable name="x_16_10" index="458" value="1.00000"/>
  <variable name="x_17_0" index="476" value="1.00000"/>
  <variable name="x_18_0" index="504" value="1.00000"/>
  <variable name="x_19_0" index="532" value="1.00000"/>
  <variable name="x_20_0" index="560" value="1.00000"/>
  <variable name="x_21_20" index="608" value="1.00000"/>
  <variable name="x_22_0" index="616" value="1.00000"/>
  <variable name="x_23_0" index="644" value="1.00000"/>
  <variable name="x_24_0" index="672" value="1.00000"/>
  <variable name="x_25_3" index="703" value="1.00000"/>
  <variable name="x_26_28" index="755" value="1.00000"/>
  <variable name="x_27_0" index="756" value="1.00000"/>
  <variable name="x_28_0" index="784" value="1.00000"/>
  <variable name="u_1" index="812" value="25.00000"/>
  <variable name="u_2" index="813" value="51.00000"/>
  <variable name="u_3" index="814" value="56.00000"/>
  <variable name="u_4" index="815" value="49.00000"/>
  <variable name="u_5" index="816" value="15.00000"/>
  <variable name="u_6" index="817" value="34.00000"/>
  <variable name="u_7" index="818" value="44.00000"/>
  <variable name="u_8" index="819" value="10.00000"/>
  <variable name="u_9" index="820" value="41.00000"/>
  <variable name="u_10" index="821" value="70.00000"/>
  <variable name="u_11" index="822" value="36.00000"/>
  <variable name="u_12" index="823" value="47.00000"/>
  <variable name="u_13" index="824" value="36.00000"/>
  <variable name="u_14" index="825" value="70.00000"/>
  <variable name="u_15" index="826" value="43.00000"/>
  <variable name="u_16" index="827" value="56.00000"/>
  <variable name="u_17" index="828" value="66.00000"/>
  <variable name="u_18" index="829" value="70.00000"/>
  <variable name="u_19" index="830" value="45.00000"/>
  <variable name="u_20" index="831" value="66.00000"/>
  <variable name="u_21" index="832" value="29.00000"/>
  <variable name="u_22" index="833" value="70.00000"/>
  <variable name="u_23" index="834" value="70.00000"/>
  <variable name="u_24" index="835" value="58.00000"/>
  <variable name="u_25" index="836" value="41.00000"/>
  <variable name="u_26" index="837" value="63.00000"/>
  <variable name="u_27" index="838" value="70.00000"/>
  <variable name="u_28" index="839" value="70.00000"/>
 </variables>
</CPLEXSolution>
