<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="10856.4"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_1_0" index="15" value="1.00000"/>
  <variable name="x_2_0" index="30" value="1.00000"/>
  <variable name="x_3_0" index="45" value="1.00000"/>
  <variable name="x_4_1" index="61" value="1.00000"/>
  <variable name="x_5_0" index="75" value="1.00000"/>
  <variable name="x_6_13" index="102" value="1.00000"/>
  <variable name="x_7_0" index="105" value="1.00000"/>
  <variable name="x_8_12" index="131" value="1.00000"/>
  <variable name="x_9_8" index="143" value="1.00000"/>
  <variable name="x_10_0" index="150" value="1.00000"/>
  <variable name="x_11_15" index="179" value="1.00000"/>
  <variable name="x_12_0" index="180" value="1.00000"/>
  <variable name="x_13_5" index="200" value="1.00000"/>
  <variable name="x_14_3" index="213" value="1.00000"/>
  <variable name="x_15_10" index="235" value="1.00000"/>
  <variable name="u_1" index="240" value="25.00000"/>
  <variable name="u_2" index="241" value="22.00000"/>
  <variable name="u_3" index="242" value="30.00000"/>
  <variable name="u_4" index="243" value="19.00000"/>
  <variable name="u_5" index="244" value="31.00000"/>
  <variable name="u_6" index="245" value="9.00000"/>
  <variable name="u_7" index="246" value="29.00000"/>
  <variable name="u_8" index="247" value="22.00000"/>
  <variable name="u_9" index="248" value="12.00000"/>
  <variable name="u_10" index="249" value="29.00000"/>
  <variable name="u_11" index="250" value="19.00000"/>
  <variable name="u_12" index="251" value="31.00000"/>
  <variable name="u_13" index="252" value="27.00000"/>
  <variable name="u_14" index="253" value="5.00000"/>
  <variable name="u_15" index="254" value="25.00000"/>
 </variables>
</CPLEXSolution>
