<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="10063.5"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_1_10" index="22" value="1.00000"/>
  <variable name="x_2_5" index="30" value="1.00000"/>
  <variable name="x_3_9" index="47" value="1.00000"/>
  <variable name="x_4_0" index="52" value="1.00000"/>
  <variable name="x_5_0" index="65" value="1.00000"/>
  <variable name="x_6_0" index="78" value="1.00000"/>
  <variable name="x_7_0" index="91" value="1.00000"/>
  <variable name="x_8_0" index="104" value="1.00000"/>
  <variable name="x_9_0" index="117" value="1.00000"/>
  <variable name="x_10_0" index="130" value="1.00000"/>
  <variable name="x_11_8" index="151" value="1.00000"/>
  <variable name="x_12_11" index="167" value="1.00000"/>
  <variable name="x_13_2" index="171" value="1.00000"/>
  <variable name="u_1" index="182" value="20.00000"/>
  <variable name="u_2" index="183" value="34.00000"/>
  <variable name="u_3" index="184" value="32.00000"/>
  <variable name="u_4" index="185" value="35.00000"/>
  <variable name="u_5" index="186" value="37.00000"/>
  <variable name="u_6" index="187" value="22.00000"/>
  <variable name="u_7" index="188" value="36.00000"/>
  <variable name="u_8" index="189" value="37.00000"/>
  <variable name="u_9" index="190" value="37.00000"/>
  <variable name="u_10" index="191" value="37.00000"/>
  <variable name="u_11" index="192" value="10.00000"/>
  <variable name="u_12" index="193" value="8.00000"/>
  <variable name="u_13" index="194" value="13.00000"/>
 </variables>
</CPLEXSolution>
