<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="12570.8"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_1_16" index="35" value="1.00000"/>
  <variable name="x_2_0" index="40" value="1.00000"/>
  <variable name="x_3_0" index="60" value="1.00000"/>
  <variable name="x_4_0" index="80" value="1.00000"/>
  <variable name="x_5_20" index="119" value="1.00000"/>
  <variable name="x_6_0" index="120" value="1.00000"/>
  <variable name="x_7_3" index="143" value="1.00000"/>
  <variable name="x_8_0" index="160" value="1.00000"/>
  <variable name="x_9_4" index="184" value="1.00000"/>
  <variable name="x_10_0" index="200" value="1.00000"/>
  <variable name="x_11_0" index="220" value="1.00000"/>
  <variable name="x_12_0" index="240" value="1.00000"/>
  <variable name="x_13_0" index="260" value="1.00000"/>
  <variable name="x_14_19" index="298" value="1.00000"/>
  <variable name="x_15_0" index="300" value="1.00000"/>
  <variable name="x_16_11" index="331" value="1.00000"/>
  <variable name="x_17_0" index="340" value="1.00000"/>
  <variable name="x_18_0" index="360" value="1.00000"/>
  <variable name="x_19_0" index="380" value="1.00000"/>
  <variable name="x_20_6" index="406" value="1.00000"/>
  <variable name="u_1" index="420" value="38.00000"/>
  <variable name="u_2" index="421" value="69.00000"/>
  <variable name="u_3" index="422" value="65.00000"/>
  <variable name="u_4" index="423" value="74.00000"/>
  <variable name="u_5" index="424" value="31.00000"/>
  <variable name="u_6" index="425" value="75.00000"/>
  <variable name="u_7" index="426" value="20.00000"/>
  <variable name="u_8" index="427" value="70.00000"/>
  <variable name="u_9" index="428" value="25.00000"/>
  <variable name="u_10" index="429" value="45.00000"/>
  <variable name="u_11" index="430" value="75.00000"/>
  <variable name="u_12" index="431" value="75.00000"/>
  <variable name="u_13" index="432" value="75.00000"/>
  <variable name="u_14" index="433" value="41.00000"/>
  <variable name="u_15" index="434" value="73.00000"/>
  <variable name="u_16" index="435" value="71.00000"/>
  <variable name="u_17" index="436" value="60.00000"/>
  <variable name="u_18" index="437" value="71.00000"/>
  <variable name="u_19" index="438" value="75.00000"/>
  <variable name="u_20" index="439" value="52.00000"/>
 </variables>
</CPLEXSolution>
