<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="15495.6"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_0_23" index="22" value="1.00000"/>
  <variable name="x_0_24" index="23" value="1.00000"/>
  <variable name="x_0_25" index="24" value="1.00000"/>
  <variable name="x_1_0" index="26" value="1.00000"/>
  <variable name="x_2_0" index="52" value="1.00000"/>
  <variable name="x_3_15" index="92" value="1.00000"/>
  <variable name="x_4_0" index="104" value="1.00000"/>
  <variable name="x_5_0" index="130" value="1.00000"/>
  <variable name="x_6_8" index="163" value="1.00000"/>
  <variable name="x_7_22" index="203" value="1.00000"/>
  <variable name="x_8_0" index="208" value="1.00000"/>
  <variable name="x_9_26" index="259" value="1.00000"/>
  <variable name="x_10_5" index="265" value="1.00000"/>
  <variable name="x_11_0" index="286" value="1.00000"/>
  <variable name="x_12_0" index="312" value="1.00000"/>
  <variable name="x_13_21" index="358" value="1.00000"/>
  <variable name="x_14_0" index="364" value="1.00000"/>
  <variable name="x_15_0" index="390" value="1.00000"/>
  <variable name="x_16_14" index="430" value="1.00000"/>
  <variable name="x_17_0" index="442" value="1.00000"/>
  <variable name="x_18_20" index="487" value="1.00000"/>
  <variable name="x_19_0" index="494" value="1.00000"/>
  <variable name="x_20_0" index="520" value="1.00000"/>
  <variable name="x_21_0" index="546" value="1.00000"/>
  <variable name="x_22_12" index="584" value="1.00000"/>
  <variable name="x_23_0" index="598" value="1.00000"/>
  <variable name="x_24_0" index="624" value="1.00000"/>
  <variable name="x_25_2" index="652" value="1.00000"/>
  <variable name="x_26_4" index="680" value="1.00000"/>
  <variable name="u_1" index="702" value="60.00000"/>
  <variable name="u_2" index="703" value="78.00000"/>
  <variable name="u_3" index="704" value="33.00000"/>
  <variable name="u_4" index="705" value="64.00000"/>
  <variable name="u_5" index="706" value="75.00000"/>
  <variable name="u_6" index="707" value="49.00000"/>
  <variable name="u_7" index="708" value="9.00000"/>
  <variable name="u_8" index="709" value="78.00000"/>
  <variable name="u_9" index="710" value="45.00000"/>
  <variable name="u_10" index="711" value="40.00000"/>
  <variable name="u_11" index="712" value="78.00000"/>
  <variable name="u_12" index="713" value="78.00000"/>
  <variable name="u_13" index="714" value="64.00000"/>
  <variable name="u_14" index="715" value="74.00000"/>
  <variable name="u_15" index="716" value="78.00000"/>
  <variable name="u_16" index="717" value="44.00000"/>
  <variable name="u_17" index="718" value="35.00000"/>
  <variable name="u_18" index="719" value="30.00000"/>
  <variable name="u_19" index="720" value="49.00000"/>
  <variable name="u_20" index="721" value="78.00000"/>
  <variable name="u_21" index="722" value="78.00000"/>
  <variable name="u_22" index="723" value="26.00000"/>
  <variable name="u_23" index="724" value="78.00000"/>
  <variable name="u_24" index="725" value="76.00000"/>
  <variable name="u_25" index="726" value="59.00000"/>
  <variable name="u_26" index="727" value="57.00000"/>
 </variables>
</CPLEXSolution>
