<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="17442"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_0_21" index="20" value="1.00000"/>
  <variable name="x_0_22" index="21" value="1.00000"/>
  <variable name="x_1_0" index="22" value="1.00000"/>
  <variable name="x_2_10" index="53" value="1.00000"/>
  <variable name="x_3_0" index="66" value="1.00000"/>
  <variable name="x_4_0" index="88" value="1.00000"/>
  <variable name="x_5_0" index="110" value="1.00000"/>
  <variable name="x_6_0" index="132" value="1.00000"/>
  <variable name="x_7_0" index="154" value="1.00000"/>
  <variable name="x_8_0" index="176" value="1.00000"/>
  <variable name="x_9_14" index="211" value="1.00000"/>
  <variable name="x_10_0" index="220" value="1.00000"/>
  <variable name="x_11_0" index="242" value="1.00000"/>
  <variable name="x_12_0" index="264" value="1.00000"/>
  <variable name="x_13_6" index="292" value="1.00000"/>
  <variable name="x_14_0" index="308" value="1.00000"/>
  <variable name="x_15_19" index="348" value="1.00000"/>
  <variable name="x_16_1" index="353" value="1.00000"/>
  <variable name="x_17_15" index="389" value="1.00000"/>
  <variable name="x_18_11" index="407" value="1.00000"/>
  <variable name="x_19_0" index="418" value="1.00000"/>
  <variable name="x_20_0" index="440" value="1.00000"/>
  <variable name="x_21_0" index="462" value="1.00000"/>
  <variable name="x_22_0" index="484" value="1.00000"/>
  <variable name="u_1" index="506" value="24.00000"/>
  <variable name="u_2" index="507" value="1.00000"/>
  <variable name="u_3" index="508" value="24.00000"/>
  <variable name="u_4" index="509" value="20.00000"/>
  <variable name="u_5" index="510" value="21.00000"/>
  <variable name="u_6" index="511" value="17.00000"/>
  <variable name="u_7" index="512" value="15.00000"/>
  <variable name="u_8" index="513" value="18.00000"/>
  <variable name="u_9" index="514" value="14.00000"/>
  <variable name="u_10" index="515" value="21.00000"/>
  <variable name="u_11" index="516" value="22.00000"/>
  <variable name="u_12" index="517" value="24.00000"/>
  <variable name="u_13" index="518" value="9.00000"/>
  <variable name="u_14" index="519" value="24.00000"/>
  <variable name="u_15" index="520" value="7.00000"/>
  <variable name="u_16" index="521" value="14.00000"/>
  <variable name="u_17" index="522" value="2.00000"/>
  <variable name="u_18" index="523" value="11.00000"/>
  <variable name="u_19" index="524" value="24.00000"/>
  <variable name="u_20" index="525" value="22.00000"/>
  <variable name="u_21" index="526" value="24.00000"/>
  <variable name="u_22" index="527" value="24.00000"/>
 </variables>
</CPLEXSolution>
