<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="9650.82"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_1_0" index="11" value="1.00000"/>
  <variable name="x_2_0" index="22" value="1.00000"/>
  <variable name="x_3_9" index="41" value="1.00000"/>
  <variable name="x_4_0" index="44" value="1.00000"/>
  <variable name="x_5_0" index="55" value="1.00000"/>
  <variable name="x_6_0" index="66" value="1.00000"/>
  <variable name="x_7_8" index="84" value="1.00000"/>
  <variable name="x_8_6" index="94" value="1.00000"/>
  <variable name="x_9_0" index="99" value="1.00000"/>
  <variable name="x_10_0" index="110" value="1.00000"/>
  <variable name="x_11_0" index="121" value="1.00000"/>
  <variable name="u_1" index="132" value="31.00000"/>
  <variable name="u_2" index="133" value="55.00000"/>
  <variable name="u_3" index="134" value="11.00000"/>
  <variable name="u_4" index="135" value="53.00000"/>
  <variable name="u_5" index="136" value="51.00000"/>
  <variable name="u_6" index="137" value="53.00000"/>
  <variable name="u_7" index="138" value="5.00000"/>
  <variable name="u_8" index="139" value="17.00000"/>
  <variable name="u_9" index="140" value="46.00000"/>
  <variable name="u_10" index="141" value="35.00000"/>
  <variable name="u_11" index="142" value="53.00000"/>
 </variables>
</CPLEXSolution>
