<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="12925.2"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_0_22" index="21" value="1.00000"/>
  <variable name="x_0_23" index="22" value="1.00000"/>
  <variable name="x_0_24" index="23" value="1.00000"/>
  <variable name="x_0_25" index="24" value="1.00000"/>
  <variable name="x_0_26" index="25" value="1.00000"/>
  <variable name="x_1_10" index="35" value="1.00000"/>
  <variable name="x_2_0" index="52" value="1.00000"/>
  <variable name="x_3_0" index="78" value="1.00000"/>
  <variable name="x_4_18" index="121" value="1.00000"/>
  <variable name="x_5_0" index="130" value="1.00000"/>
  <variable name="x_6_0" index="156" value="1.00000"/>
  <variable name="x_7_0" index="182" value="1.00000"/>
  <variable name="x_8_16" index="223" value="1.00000"/>
  <variable name="x_9_21" index="254" value="1.00000"/>
  <variable name="x_10_12" index="271" value="1.00000"/>
  <variable name="x_11_0" index="286" value="1.00000"/>
  <variable name="x_12_0" index="312" value="1.00000"/>
  <variable name="x_13_8" index="346" value="1.00000"/>
  <variable name="x_14_0" index="364" value="1.00000"/>
  <variable name="x_15_0" index="390" value="1.00000"/>
  <variable name="x_16_14" index="430" value="1.00000"/>
  <variable name="x_17_0" index="442" value="1.00000"/>
  <variable name="x_18_0" index="468" value="1.00000"/>
  <variable name="x_19_0" index="494" value="1.00000"/>
  <variable name="x_20_7" index="527" value="1.00000"/>
  <variable name="x_21_17" index="563" value="1.00000"/>
  <variable name="x_22_0" index="572" value="1.00000"/>
  <variable name="x_23_0" index="598" value="1.00000"/>
  <variable name="x_24_0" index="624" value="1.00000"/>
  <variable name="x_25_0" index="650" value="1.00000"/>
  <variable name="x_26_5" index="681" value="1.00000"/>
  <variable name="u_1" index="702" value="27.00000"/>
  <variable name="u_2" index="703" value="66.00000"/>
  <variable name="u_3" index="704" value="55.00000"/>
  <variable name="u_4" index="705" value="50.00000"/>
  <variable name="u_5" index="706" value="57.00000"/>
  <variable name="u_6" index="707" value="65.00000"/>
  <variable name="u_7" index="708" value="35.00000"/>
  <variable name="u_8" index="709" value="37.00000"/>
  <variable name="u_9" index="710" value="41.00000"/>
  <variable name="u_10" index="711" value="47.00000"/>
  <variable name="u_11" index="712" value="66.00000"/>
  <variable name="u_12" index="713" value="66.00000"/>
  <variable name="u_13" index="714" value="9.00000"/>
  <variable name="u_14" index="715" value="57.00000"/>
  <variable name="u_15" index="716" value="59.00000"/>
  <variable name="u_16" index="717" value="54.00000"/>
  <variable name="u_17" index="718" value="66.00000"/>
  <variable name="u_18" index="719" value="66.00000"/>
  <variable name="u_19" index="720" value="45.00000"/>
  <variable name="u_20" index="721" value="18.00000"/>
  <variable name="u_21" index="722" value="42.00000"/>
  <variable name="u_22" index="723" value="66.00000"/>
  <variable name="u_23" index="724" value="66.00000"/>
  <variable name="u_24" index="725" value="66.00000"/>
  <variable name="u_25" index="726" value="48.00000"/>
  <variable name="u_26" index="727" value="10.00000"/>
 </variables>
</CPLEXSolution>
