<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="5874.88"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_1_0" index="12" value="1.00000"/>
  <variable name="x_2_0" index="24" value="1.00000"/>
  <variable name="x_3_9" index="44" value="1.00000"/>
  <variable name="x_4_6" index="53" value="1.00000"/>
  <variable name="x_5_0" index="60" value="1.00000"/>
  <variable name="x_6_5" index="77" value="1.00000"/>
  <variable name="x_7_0" index="84" value="1.00000"/>
  <variable name="x_8_4" index="100" value="1.00000"/>
  <variable name="x_9_2" index="110" value="1.00000"/>
  <variable name="x_10_3" index="123" value="1.00000"/>
  <variable name="x_11_0" index="132" value="1.00000"/>
  <variable name="x_12_0" index="144" value="1.00000"/>
  <variable name="u_1" index="156" value="25.00000"/>
  <variable name="u_2" index="157" value="25.00000"/>
  <variable name="u_3" index="158" value="16.00000"/>
  <variable name="u_4" index="159" value="14.00000"/>
  <variable name="u_5" index="160" value="25.00000"/>
  <variable name="u_6" index="161" value="16.00000"/>
  <variable name="u_7" index="162" value="25.00000"/>
  <variable name="u_8" index="163" value="12.00000"/>
  <variable name="u_9" index="164" value="20.00000"/>
  <variable name="u_10" index="165" value="2.00000"/>
  <variable name="u_11" index="166" value="23.00000"/>
  <variable name="u_12" index="167" value="25.00000"/>
 </variables>
</CPLEXSolution>
