<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="14121.6"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_1_3" index="20" value="1.00000"/>
  <variable name="x_2_0" index="36" value="1.00000"/>
  <variable name="x_3_0" index="54" value="1.00000"/>
  <variable name="x_4_0" index="72" value="1.00000"/>
  <variable name="x_5_0" index="90" value="1.00000"/>
  <variable name="x_6_12" index="119" value="1.00000"/>
  <variable name="x_7_0" index="126" value="1.00000"/>
  <variable name="x_8_0" index="144" value="1.00000"/>
  <variable name="x_9_10" index="171" value="1.00000"/>
  <variable name="x_10_0" index="180" value="1.00000"/>
  <variable name="x_11_0" index="198" value="1.00000"/>
  <variable name="x_12_0" index="216" value="1.00000"/>
  <variable name="x_13_7" index="241" value="1.00000"/>
  <variable name="x_14_13" index="265" value="1.00000"/>
  <variable name="x_15_16" index="285" value="1.00000"/>
  <variable name="x_16_0" index="288" value="1.00000"/>
  <variable name="x_17_0" index="306" value="1.00000"/>
  <variable name="x_18_4" index="328" value="1.00000"/>
  <variable name="u_1" index="342" value="16.00000"/>
  <variable name="u_2" index="343" value="50.00000"/>
  <variable name="u_3" index="344" value="66.00000"/>
  <variable name="u_4" index="345" value="66.00000"/>
  <variable name="u_5" index="346" value="61.00000"/>
  <variable name="u_6" index="347" value="45.00000"/>
  <variable name="u_7" index="348" value="66.00000"/>
  <variable name="u_8" index="349" value="36.00000"/>
  <variable name="u_9" index="350" value="42.00000"/>
  <variable name="u_10" index="351" value="50.00000"/>
  <variable name="u_11" index="352" value="56.00000"/>
  <variable name="u_12" index="353" value="59.00000"/>
  <variable name="u_13" index="354" value="27.00000"/>
  <variable name="u_14" index="355" value="14.00000"/>
  <variable name="u_15" index="356" value="34.00000"/>
  <variable name="u_16" index="357" value="65.00000"/>
  <variable name="u_17" index="358" value="50.00000"/>
  <variable name="u_18" index="359" value="35.00000"/>
 </variables>
</CPLEXSolution>
