<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="6642.84"
  />
 <variables>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_1_0" index="15" value="1.00000"/>
  <variable name="x_2_0" index="30" value="1.00000"/>
  <variable name="x_3_13" index="57" value="1.00000"/>
  <variable name="x_4_1" index="61" value="1.00000"/>
  <variable name="x_5_0" index="75" value="1.00000"/>
  <variable name="x_6_3" index="93" value="1.00000"/>
  <variable name="x_7_12" index="116" value="1.00000"/>
  <variable name="x_8_0" index="120" value="1.00000"/>
  <variable name="x_9_0" index="135" value="1.00000"/>
  <variable name="x_10_5" index="155" value="1.00000"/>
  <variable name="x_11_7" index="172" value="1.00000"/>
  <variable name="x_12_0" index="180" value="1.00000"/>
  <variable name="x_13_2" index="197" value="1.00000"/>
  <variable name="x_14_0" index="210" value="1.00000"/>
  <variable name="x_15_10" index="235" value="1.00000"/>
  <variable name="u_1" index="240" value="71.00000"/>
  <variable name="u_2" index="241" value="65.00000"/>
  <variable name="u_3" index="242" value="54.00000"/>
  <variable name="u_4" index="243" value="46.00000"/>
  <variable name="u_5" index="244" value="71.00000"/>
  <variable name="u_6" index="245" value="47.00000"/>
  <variable name="u_7" index="246" value="36.00000"/>
  <variable name="u_8" index="247" value="71.00000"/>
  <variable name="u_9" index="248" value="58.00000"/>
  <variable name="u_10" index="249" value="46.00000"/>
  <variable name="u_11" index="250" value="7.00000"/>
  <variable name="u_12" index="251" value="67.00000"/>
  <variable name="u_13" index="252" value="63.00000"/>
  <variable name="u_14" index="253" value="31.00000"/>
  <variable name="u_15" index="254" value="34.00000"/>
 </variables>
</CPLEXSolution>
