<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="8812.64"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_1_0" index="22" value="1.00000"/>
  <variable name="x_2_0" index="44" value="1.00000"/>
  <variable name="x_3_0" index="66" value="1.00000"/>
  <variable name="x_4_21" index="108" value="1.00000"/>
  <variable name="x_5_0" index="110" value="1.00000"/>
  <variable name="x_6_1" index="133" value="1.00000"/>
  <variable name="x_7_15" index="168" value="1.00000"/>
  <variable name="x_8_0" index="176" value="1.00000"/>
  <variable name="x_9_0" index="198" value="1.00000"/>
  <variable name="x_10_5" index="225" value="1.00000"/>
  <variable name="x_11_14" index="255" value="1.00000"/>
  <variable name="x_12_0" index="264" value="1.00000"/>
  <variable name="x_13_0" index="286" value="1.00000"/>
  <variable name="x_14_0" index="308" value="1.00000"/>
  <variable name="x_15_0" index="330" value="1.00000"/>
  <variable name="x_16_12" index="364" value="1.00000"/>
  <variable name="x_17_0" index="374" value="1.00000"/>
  <variable name="x_18_19" index="414" value="1.00000"/>
  <variable name="x_19_22" index="439" value="1.00000"/>
  <variable name="x_20_7" index="447" value="1.00000"/>
  <variable name="x_21_0" index="462" value="1.00000"/>
  <variable name="x_22_11" index="495" value="1.00000"/>
  <variable name="u_1" index="506" value="35.00000"/>
  <variable name="u_2" index="507" value="21.00000"/>
  <variable name="u_3" index="508" value="23.00000"/>
  <variable name="u_4" index="509" value="10.00000"/>
  <variable name="u_5" index="510" value="31.00000"/>
  <variable name="u_6" index="511" value="33.00000"/>
  <variable name="u_7" index="512" value="23.00000"/>
  <variable name="u_8" index="513" value="34.00000"/>
  <variable name="u_9" index="514" value="29.00000"/>
  <variable name="u_10" index="515" value="16.00000"/>
  <variable name="u_11" index="516" value="31.00000"/>
  <variable name="u_12" index="517" value="35.00000"/>
  <variable name="u_13" index="518" value="27.00000"/>
  <variable name="u_14" index="519" value="33.00000"/>
  <variable name="u_15" index="520" value="35.00000"/>
  <variable name="u_16" index="521" value="9.00000"/>
  <variable name="u_17" index="522" value="35.00000"/>
  <variable name="u_18" index="523" value="5.00000"/>
  <variable name="u_19" index="524" value="18.00000"/>
  <variable name="u_20" index="525" value="6.00000"/>
  <variable name="u_21" index="526" value="35.00000"/>
  <variable name="u_22" index="527" value="19.00000"/>
 </variables>
</CPLEXSolution>
