<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="18540.1"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_23" index="22" value="1.00000"/>
  <variable name="x_0_24" index="23" value="1.00000"/>
  <variable name="x_0_25" index="24" value="1.00000"/>
  <variable name="x_1_19" index="43" value="1.00000"/>
  <variable name="x_2_0" index="50" value="1.00000"/>
  <variable name="x_3_12" index="86" value="1.00000"/>
  <variable name="x_4_0" index="100" value="1.00000"/>
  <variable name="x_5_11" index="135" value="1.00000"/>
  <variable name="x_6_22" index="171" value="1.00000"/>
  <variable name="x_7_9" index="183" value="1.00000"/>
  <variable name="x_8_15" index="214" value="1.00000"/>
  <variable name="x_9_13" index="237" value="1.00000"/>
  <variable name="x_10_20" index="269" value="1.00000"/>
  <variable name="x_11_0" index="275" value="1.00000"/>
  <variable name="x_12_0" index="300" value="1.00000"/>
  <variable name="x_13_0" index="325" value="1.00000"/>
  <variable name="x_14_0" index="350" value="1.00000"/>
  <variable name="x_15_18" index="392" value="1.00000"/>
  <variable name="x_16_4" index="404" value="1.00000"/>
  <variable name="x_17_14" index="439" value="1.00000"/>
  <variable name="x_18_0" index="450" value="1.00000"/>
  <variable name="x_19_0" index="475" value="1.00000"/>
  <variable name="x_20_2" index="502" value="1.00000"/>
  <variable name="x_21_0" index="525" value="1.00000"/>
  <variable name="x_22_21" index="571" value="1.00000"/>
  <variable name="x_23_0" index="575" value="1.00000"/>
  <variable name="x_24_0" index="600" value="1.00000"/>
  <variable name="x_25_0" index="625" value="1.00000"/>
  <variable name="u_1" index="650" value="38.00000"/>
  <variable name="u_2" index="651" value="60.00000"/>
  <variable name="u_3" index="652" value="12.00000"/>
  <variable name="u_4" index="653" value="58.00000"/>
  <variable name="u_5" index="654" value="16.00000"/>
  <variable name="u_6" index="655" value="30.00000"/>
  <variable name="u_7" index="656" value="26.00000"/>
  <variable name="u_8" index="657" value="2.00000"/>
  <variable name="u_9" index="658" value="53.00000"/>
  <variable name="u_10" index="659" value="39.00000"/>
  <variable name="u_11" index="660" value="55.00000"/>
  <variable name="u_12" index="661" value="55.00000"/>
  <variable name="u_13" index="662" value="60.00000"/>
  <variable name="u_14" index="663" value="60.00000"/>
  <variable name="u_15" index="664" value="29.00000"/>
  <variable name="u_16" index="665" value="49.00000"/>
  <variable name="u_17" index="666" value="39.00000"/>
  <variable name="u_18" index="667" value="60.00000"/>
  <variable name="u_19" index="668" value="59.00000"/>
  <variable name="u_20" index="669" value="42.00000"/>
  <variable name="u_21" index="670" value="59.00000"/>
  <variable name="u_22" index="671" value="55.00000"/>
  <variable name="u_23" index="672" value="41.00000"/>
  <variable name="u_24" index="673" value="59.00000"/>
  <variable name="u_25" index="674" value="58.00000"/>
 </variables>
</CPLEXSolution>
