<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="11833.5"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_1_13" index="29" value="1.00000"/>
  <variable name="x_2_3" index="36" value="1.00000"/>
  <variable name="x_3_0" index="51" value="1.00000"/>
  <variable name="x_4_0" index="68" value="1.00000"/>
  <variable name="x_5_0" index="85" value="1.00000"/>
  <variable name="x_6_0" index="102" value="1.00000"/>
  <variable name="x_7_12" index="130" value="1.00000"/>
  <variable name="x_8_0" index="136" value="1.00000"/>
  <variable name="x_9_4" index="157" value="1.00000"/>
  <variable name="x_10_0" index="170" value="1.00000"/>
  <variable name="x_11_10" index="197" value="1.00000"/>
  <variable name="x_12_0" index="204" value="1.00000"/>
  <variable name="x_13_8" index="229" value="1.00000"/>
  <variable name="x_14_0" index="238" value="1.00000"/>
  <variable name="x_15_14" index="269" value="1.00000"/>
  <variable name="x_16_6" index="278" value="1.00000"/>
  <variable name="x_17_9" index="298" value="1.00000"/>
  <variable name="u_1" index="306" value="24.00000"/>
  <variable name="u_2" index="307" value="38.00000"/>
  <variable name="u_3" index="308" value="44.00000"/>
  <variable name="u_4" index="309" value="44.00000"/>
  <variable name="u_5" index="310" value="44.00000"/>
  <variable name="u_6" index="311" value="43.00000"/>
  <variable name="u_7" index="312" value="9.00000"/>
  <variable name="u_8" index="313" value="42.00000"/>
  <variable name="u_9" index="314" value="11.00000"/>
  <variable name="u_10" index="315" value="39.00000"/>
  <variable name="u_11" index="316" value="7.00000"/>
  <variable name="u_12" index="317" value="40.00000"/>
  <variable name="u_13" index="318" value="39.00000"/>
  <variable name="u_14" index="319" value="44.00000"/>
  <variable name="u_15" index="320" value="22.00000"/>
  <variable name="u_16" index="321" value="5.00000"/>
  <variable name="u_17" index="322" value="3.00000"/>
 </variables>
</CPLEXSolution>
