<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="11747.1"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_0_21" index="20" value="1.00000"/>
  <variable name="x_0_22" index="21" value="1.00000"/>
  <variable name="x_0_26" index="25" value="1.00000"/>
  <variable name="x_1_18" index="43" value="1.00000"/>
  <variable name="x_2_0" index="52" value="1.00000"/>
  <variable name="x_3_10" index="87" value="1.00000"/>
  <variable name="x_4_6" index="109" value="1.00000"/>
  <variable name="x_5_17" index="146" value="1.00000"/>
  <variable name="x_6_5" index="161" value="1.00000"/>
  <variable name="x_7_0" index="182" value="1.00000"/>
  <variable name="x_8_9" index="216" value="1.00000"/>
  <variable name="x_9_0" index="234" value="1.00000"/>
  <variable name="x_10_0" index="260" value="1.00000"/>
  <variable name="x_11_0" index="286" value="1.00000"/>
  <variable name="x_12_15" index="326" value="1.00000"/>
  <variable name="x_13_7" index="345" value="1.00000"/>
  <variable name="x_14_11" index="375" value="1.00000"/>
  <variable name="x_15_23" index="412" value="1.00000"/>
  <variable name="x_16_0" index="416" value="1.00000"/>
  <variable name="x_17_0" index="442" value="1.00000"/>
  <variable name="x_18_13" index="481" value="1.00000"/>
  <variable name="x_19_16" index="510" value="1.00000"/>
  <variable name="x_20_24" index="543" value="1.00000"/>
  <variable name="x_21_0" index="546" value="1.00000"/>
  <variable name="x_22_0" index="572" value="1.00000"/>
  <variable name="x_23_25" index="622" value="1.00000"/>
  <variable name="x_24_0" index="624" value="1.00000"/>
  <variable name="x_25_0" index="650" value="1.00000"/>
  <variable name="x_26_8" index="684" value="1.00000"/>
  <variable name="u_1" index="702" value="37.00000"/>
  <variable name="u_2" index="703" value="68.00000"/>
  <variable name="u_3" index="704" value="64.00000"/>
  <variable name="u_4" index="705" value="21.00000"/>
  <variable name="u_5" index="706" value="62.00000"/>
  <variable name="u_6" index="707" value="34.00000"/>
  <variable name="u_7" index="708" value="76.00000"/>
  <variable name="u_8" index="709" value="27.00000"/>
  <variable name="u_9" index="710" value="76.00000"/>
  <variable name="u_10" index="711" value="76.00000"/>
  <variable name="u_11" index="712" value="76.00000"/>
  <variable name="u_12" index="713" value="15.00000"/>
  <variable name="u_13" index="714" value="69.00000"/>
  <variable name="u_14" index="715" value="16.00000"/>
  <variable name="u_15" index="716" value="16.00000"/>
  <variable name="u_16" index="717" value="76.00000"/>
  <variable name="u_17" index="718" value="76.00000"/>
  <variable name="u_18" index="719" value="65.00000"/>
  <variable name="u_19" index="720" value="67.00000"/>
  <variable name="u_20" index="721" value="19.00000"/>
  <variable name="u_21" index="722" value="76.00000"/>
  <variable name="u_22" index="723" value="76.00000"/>
  <variable name="u_23" index="724" value="54.00000"/>
  <variable name="u_24" index="725" value="76.00000"/>
  <variable name="u_25" index="726" value="70.00000"/>
  <variable name="u_26" index="727" value="23.00000"/>
 </variables>
</CPLEXSolution>
