<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="18083.3"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_21" index="20" value="1.00000"/>
  <variable name="x_0_22" index="21" value="1.00000"/>
  <variable name="x_1_0" index="22" value="1.00000"/>
  <variable name="x_2_0" index="44" value="1.00000"/>
  <variable name="x_3_1" index="67" value="1.00000"/>
  <variable name="x_4_0" index="88" value="1.00000"/>
  <variable name="x_5_20" index="129" value="1.00000"/>
  <variable name="x_6_11" index="142" value="1.00000"/>
  <variable name="x_7_4" index="158" value="1.00000"/>
  <variable name="x_8_7" index="183" value="1.00000"/>
  <variable name="x_9_15" index="212" value="1.00000"/>
  <variable name="x_10_0" index="220" value="1.00000"/>
  <variable name="x_11_0" index="242" value="1.00000"/>
  <variable name="x_12_0" index="264" value="1.00000"/>
  <variable name="x_13_0" index="286" value="1.00000"/>
  <variable name="x_14_5" index="313" value="1.00000"/>
  <variable name="x_15_0" index="330" value="1.00000"/>
  <variable name="x_16_0" index="352" value="1.00000"/>
  <variable name="x_17_0" index="374" value="1.00000"/>
  <variable name="x_18_0" index="396" value="1.00000"/>
  <variable name="x_19_0" index="418" value="1.00000"/>
  <variable name="x_20_0" index="440" value="1.00000"/>
  <variable name="x_21_18" index="480" value="1.00000"/>
  <variable name="x_22_19" index="503" value="1.00000"/>
  <variable name="u_1" index="506" value="29.00000"/>
  <variable name="u_2" index="507" value="29.00000"/>
  <variable name="u_3" index="508" value="5.00000"/>
  <variable name="u_4" index="509" value="29.00000"/>
  <variable name="u_5" index="510" value="19.00000"/>
  <variable name="u_6" index="511" value="4.00000"/>
  <variable name="u_7" index="512" value="26.00000"/>
  <variable name="u_8" index="513" value="17.00000"/>
  <variable name="u_9" index="514" value="15.00000"/>
  <variable name="u_10" index="515" value="29.00000"/>
  <variable name="u_11" index="516" value="29.00000"/>
  <variable name="u_12" index="517" value="29.00000"/>
  <variable name="u_13" index="518" value="28.00000"/>
  <variable name="u_14" index="519" value="7.00000"/>
  <variable name="u_15" index="520" value="25.00000"/>
  <variable name="u_16" index="521" value="29.00000"/>
  <variable name="u_17" index="522" value="24.00000"/>
  <variable name="u_18" index="523" value="29.00000"/>
  <variable name="u_19" index="524" value="25.00000"/>
  <variable name="u_20" index="525" value="29.00000"/>
  <variable name="u_21" index="526" value="4.00000"/>
  <variable name="u_22" index="527" value="3.00000"/>
 </variables>
</CPLEXSolution>
