<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="6073.61"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_1_0" index="10" value="1.00000"/>
  <variable name="x_2_0" index="20" value="1.00000"/>
  <variable name="x_3_5" index="34" value="1.00000"/>
  <variable name="x_4_10" index="49" value="1.00000"/>
  <variable name="x_5_0" index="50" value="1.00000"/>
  <variable name="x_6_0" index="60" value="1.00000"/>
  <variable name="x_7_0" index="70" value="1.00000"/>
  <variable name="x_8_4" index="84" value="1.00000"/>
  <variable name="x_9_0" index="90" value="1.00000"/>
  <variable name="x_10_7" index="107" value="1.00000"/>
  <variable name="u_1" index="110" value="56.00000"/>
  <variable name="u_2" index="111" value="52.00000"/>
  <variable name="u_3" index="112" value="38.00000"/>
  <variable name="u_4" index="113" value="48.00000"/>
  <variable name="u_5" index="114" value="42.00000"/>
  <variable name="u_6" index="115" value="44.00000"/>
  <variable name="u_7" index="116" value="54.00000"/>
  <variable name="u_8" index="117" value="36.00000"/>
  <variable name="u_9" index="118" value="56.00000"/>
  <variable name="u_10" index="119" value="49.00000"/>
 </variables>
</CPLEXSolution>
