<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="7483.9"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_1_0" index="13" value="1.00000"/>
  <variable name="x_2_7" index="32" value="1.00000"/>
  <variable name="x_3_0" index="39" value="1.00000"/>
  <variable name="x_4_5" index="56" value="1.00000"/>
  <variable name="x_5_0" index="65" value="1.00000"/>
  <variable name="x_6_0" index="78" value="1.00000"/>
  <variable name="x_7_12" index="102" value="1.00000"/>
  <variable name="x_8_4" index="108" value="1.00000"/>
  <variable name="x_9_1" index="118" value="1.00000"/>
  <variable name="x_10_3" index="133" value="1.00000"/>
  <variable name="x_11_0" index="143" value="1.00000"/>
  <variable name="x_12_0" index="156" value="1.00000"/>
  <variable name="x_13_6" index="175" value="1.00000"/>
  <variable name="u_1" index="182" value="39.00000"/>
  <variable name="u_2" index="183" value="6.00000"/>
  <variable name="u_3" index="184" value="39.00000"/>
  <variable name="u_4" index="185" value="21.00000"/>
  <variable name="u_5" index="186" value="39.00000"/>
  <variable name="u_6" index="187" value="38.00000"/>
  <variable name="u_7" index="188" value="29.00000"/>
  <variable name="u_8" index="189" value="5.00000"/>
  <variable name="u_9" index="190" value="26.00000"/>
  <variable name="u_10" index="191" value="17.00000"/>
  <variable name="u_11" index="192" value="38.00000"/>
  <variable name="u_12" index="193" value="41.00000"/>
  <variable name="u_13" index="194" value="13.00000"/>
 </variables>
</CPLEXSolution>
