<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="12648.3"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_1_0" index="17" value="1.00000"/>
  <variable name="x_2_9" index="42" value="1.00000"/>
  <variable name="x_3_0" index="51" value="1.00000"/>
  <variable name="x_4_13" index="80" value="1.00000"/>
  <variable name="x_5_0" index="85" value="1.00000"/>
  <variable name="x_6_7" index="108" value="1.00000"/>
  <variable name="x_7_0" index="119" value="1.00000"/>
  <variable name="x_8_0" index="136" value="1.00000"/>
  <variable name="x_9_0" index="153" value="1.00000"/>
  <variable name="x_10_0" index="170" value="1.00000"/>
  <variable name="x_11_0" index="187" value="1.00000"/>
  <variable name="x_12_0" index="204" value="1.00000"/>
  <variable name="x_13_1" index="222" value="1.00000"/>
  <variable name="x_14_16" index="253" value="1.00000"/>
  <variable name="x_15_12" index="267" value="1.00000"/>
  <variable name="x_16_0" index="272" value="1.00000"/>
  <variable name="x_17_0" index="289" value="1.00000"/>
  <variable name="u_1" index="306" value="52.00000"/>
  <variable name="u_2" index="307" value="25.00000"/>
  <variable name="u_3" index="308" value="50.00000"/>
  <variable name="u_4" index="309" value="12.00000"/>
  <variable name="u_5" index="310" value="53.00000"/>
  <variable name="u_6" index="311" value="24.00000"/>
  <variable name="u_7" index="312" value="51.00000"/>
  <variable name="u_8" index="313" value="45.00000"/>
  <variable name="u_9" index="314" value="46.00000"/>
  <variable name="u_10" index="315" value="53.00000"/>
  <variable name="u_11" index="316" value="46.00000"/>
  <variable name="u_12" index="317" value="58.00000"/>
  <variable name="u_13" index="318" value="42.00000"/>
  <variable name="u_14" index="319" value="59.00000"/>
  <variable name="u_15" index="320" value="32.00000"/>
  <variable name="u_16" index="321" value="61.00000"/>
  <variable name="u_17" index="322" value="61.00000"/>
 </variables>
</CPLEXSolution>
