<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="18643.6"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_0_21" index="20" value="1.00000"/>
  <variable name="x_0_22" index="21" value="1.00000"/>
  <variable name="x_0_26" index="25" value="1.00000"/>
  <variable name="x_0_30" index="29" value="1.00000"/>
  <variable name="x_1_0" index="30" value="1.00000"/>
  <variable name="x_2_0" index="60" value="1.00000"/>
  <variable name="x_3_18" index="107" value="1.00000"/>
  <variable name="x_4_28" index="147" value="1.00000"/>
  <variable name="x_5_15" index="164" value="1.00000"/>
  <variable name="x_6_9" index="188" value="1.00000"/>
  <variable name="x_7_16" index="225" value="1.00000"/>
  <variable name="x_8_0" index="240" value="1.00000"/>
  <variable name="x_9_13" index="282" value="1.00000"/>
  <variable name="x_10_14" index="313" value="1.00000"/>
  <variable name="x_11_0" index="330" value="1.00000"/>
  <variable name="x_12_25" index="384" value="1.00000"/>
  <variable name="x_13_24" index="413" value="1.00000"/>
  <variable name="x_14_0" index="420" value="1.00000"/>
  <variable name="x_15_3" index="453" value="1.00000"/>
  <variable name="x_16_0" index="480" value="1.00000"/>
  <variable name="x_17_0" index="510" value="1.00000"/>
  <variable name="x_18_29" index="568" value="1.00000"/>
  <variable name="x_19_0" index="570" value="1.00000"/>
  <variable name="x_20_27" index="626" value="1.00000"/>
  <variable name="x_21_0" index="630" value="1.00000"/>
  <variable name="x_22_0" index="660" value="1.00000"/>
  <variable name="x_23_0" index="690" value="1.00000"/>
  <variable name="x_24_0" index="720" value="1.00000"/>
  <variable name="x_25_23" index="773" value="1.00000"/>
  <variable name="x_26_0" index="780" value="1.00000"/>
  <variable name="x_27_0" index="810" value="1.00000"/>
  <variable name="x_28_0" index="840" value="1.00000"/>
  <variable name="x_29_11" index="881" value="1.00000"/>
  <variable name="x_30_0" index="900" value="1.00000"/>
  <variable name="u_1" index="930" value="63.00000"/>
  <variable name="u_2" index="931" value="67.00000"/>
  <variable name="u_3" index="932" value="32.00000"/>
  <variable name="u_4" index="933" value="24.00000"/>
  <variable name="u_5" index="934" value="4.00000"/>
  <variable name="u_6" index="935" value="6.00000"/>
  <variable name="u_7" index="936" value="13.00000"/>
  <variable name="u_8" index="937" value="71.00000"/>
  <variable name="u_9" index="938" value="30.00000"/>
  <variable name="u_10" index="939" value="32.00000"/>
  <variable name="u_11" index="940" value="71.00000"/>
  <variable name="u_12" index="941" value="24.00000"/>
  <variable name="u_13" index="942" value="53.00000"/>
  <variable name="u_14" index="943" value="71.00000"/>
  <variable name="u_15" index="944" value="9.00000"/>
  <variable name="u_16" index="945" value="62.00000"/>
  <variable name="u_17" index="946" value="71.00000"/>
  <variable name="u_18" index="947" value="38.00000"/>
  <variable name="u_19" index="948" value="62.00000"/>
  <variable name="u_20" index="949" value="68.00000"/>
  <variable name="u_21" index="950" value="71.00000"/>
  <variable name="u_22" index="951" value="61.00000"/>
  <variable name="u_23" index="952" value="71.00000"/>
  <variable name="u_24" index="953" value="71.00000"/>
  <variable name="u_25" index="954" value="56.00000"/>
  <variable name="u_26" index="955" value="71.00000"/>
  <variable name="u_27" index="956" value="71.00000"/>
  <variable name="u_28" index="957" value="70.00000"/>
  <variable name="u_29" index="958" value="57.00000"/>
  <variable name="u_30" index="959" value="71.00000"/>
 </variables>
</CPLEXSolution>
