<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="16134.6"
  />
 <variables>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_0_21" index="20" value="1.00000"/>
  <variable name="x_0_23" index="22" value="1.00000"/>
  <variable name="x_1_25" index="49" value="1.00000"/>
  <variable name="x_2_0" index="50" value="1.00000"/>
  <variable name="x_3_12" index="86" value="1.00000"/>
  <variable name="x_4_0" index="100" value="1.00000"/>
  <variable name="x_5_2" index="127" value="1.00000"/>
  <variable name="x_6_8" index="157" value="1.00000"/>
  <variable name="x_7_1" index="176" value="1.00000"/>
  <variable name="x_8_24" index="223" value="1.00000"/>
  <variable name="x_9_20" index="244" value="1.00000"/>
  <variable name="x_10_15" index="264" value="1.00000"/>
  <variable name="x_11_0" index="275" value="1.00000"/>
  <variable name="x_12_0" index="300" value="1.00000"/>
  <variable name="x_13_0" index="325" value="1.00000"/>
  <variable name="x_14_16" index="365" value="1.00000"/>
  <variable name="x_15_0" index="375" value="1.00000"/>
  <variable name="x_16_22" index="421" value="1.00000"/>
  <variable name="x_17_0" index="425" value="1.00000"/>
  <variable name="x_18_0" index="450" value="1.00000"/>
  <variable name="x_19_0" index="475" value="1.00000"/>
  <variable name="x_20_0" index="500" value="1.00000"/>
  <variable name="x_21_0" index="525" value="1.00000"/>
  <variable name="x_22_13" index="563" value="1.00000"/>
  <variable name="x_23_0" index="575" value="1.00000"/>
  <variable name="x_24_0" index="600" value="1.00000"/>
  <variable name="x_25_0" index="625" value="1.00000"/>
  <variable name="u_1" index="650" value="51.00000"/>
  <variable name="u_2" index="651" value="77.00000"/>
  <variable name="u_3" index="652" value="56.00000"/>
  <variable name="u_4" index="653" value="77.00000"/>
  <variable name="u_5" index="654" value="23.00000"/>
  <variable name="u_6" index="655" value="11.00000"/>
  <variable name="u_7" index="656" value="38.00000"/>
  <variable name="u_8" index="657" value="12.00000"/>
  <variable name="u_9" index="658" value="11.00000"/>
  <variable name="u_10" index="659" value="67.00000"/>
  <variable name="u_11" index="660" value="77.00000"/>
  <variable name="u_12" index="661" value="69.00000"/>
  <variable name="u_13" index="662" value="77.00000"/>
  <variable name="u_14" index="663" value="45.00000"/>
  <variable name="u_15" index="664" value="77.00000"/>
  <variable name="u_16" index="665" value="48.00000"/>
  <variable name="u_17" index="666" value="72.00000"/>
  <variable name="u_18" index="667" value="68.00000"/>
  <variable name="u_19" index="668" value="69.00000"/>
  <variable name="u_20" index="669" value="64.00000"/>
  <variable name="u_21" index="670" value="77.00000"/>
  <variable name="u_22" index="671" value="74.00000"/>
  <variable name="u_23" index="672" value="77.00000"/>
  <variable name="u_24" index="673" value="63.00000"/>
  <variable name="u_25" index="674" value="74.00000"/>
 </variables>
</CPLEXSolution>
