<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="14244"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_1_0" index="19" value="1.00000"/>
  <variable name="x_2_12" index="49" value="1.00000"/>
  <variable name="x_3_0" index="57" value="1.00000"/>
  <variable name="x_4_0" index="76" value="1.00000"/>
  <variable name="x_5_18" index="112" value="1.00000"/>
  <variable name="x_6_5" index="119" value="1.00000"/>
  <variable name="x_7_3" index="136" value="1.00000"/>
  <variable name="x_8_9" index="160" value="1.00000"/>
  <variable name="x_9_1" index="172" value="1.00000"/>
  <variable name="x_10_0" index="190" value="1.00000"/>
  <variable name="x_11_0" index="209" value="1.00000"/>
  <variable name="x_12_0" index="228" value="1.00000"/>
  <variable name="x_13_17" index="263" value="1.00000"/>
  <variable name="x_14_0" index="266" value="1.00000"/>
  <variable name="x_15_14" index="299" value="1.00000"/>
  <variable name="x_16_11" index="315" value="1.00000"/>
  <variable name="x_17_0" index="323" value="1.00000"/>
  <variable name="x_18_0" index="342" value="1.00000"/>
  <variable name="x_19_0" index="361" value="1.00000"/>
  <variable name="u_1" index="380" value="65.00000"/>
  <variable name="u_2" index="381" value="14.00000"/>
  <variable name="u_3" index="382" value="66.00000"/>
  <variable name="u_4" index="383" value="66.00000"/>
  <variable name="u_5" index="384" value="30.00000"/>
  <variable name="u_6" index="385" value="26.00000"/>
  <variable name="u_7" index="386" value="21.00000"/>
  <variable name="u_8" index="387" value="33.00000"/>
  <variable name="u_9" index="388" value="51.00000"/>
  <variable name="u_10" index="389" value="66.00000"/>
  <variable name="u_11" index="390" value="52.00000"/>
  <variable name="u_12" index="391" value="61.00000"/>
  <variable name="u_13" index="392" value="33.00000"/>
  <variable name="u_14" index="393" value="63.00000"/>
  <variable name="u_15" index="394" value="41.00000"/>
  <variable name="u_16" index="395" value="30.00000"/>
  <variable name="u_17" index="396" value="60.00000"/>
  <variable name="u_18" index="397" value="64.00000"/>
  <variable name="u_19" index="398" value="64.00000"/>
 </variables>
</CPLEXSolution>
