<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="7754.55"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_1_0" index="16" value="1.00000"/>
  <variable name="x_2_0" index="32" value="1.00000"/>
  <variable name="x_3_0" index="48" value="1.00000"/>
  <variable name="x_4_13" index="76" value="1.00000"/>
  <variable name="x_5_3" index="83" value="1.00000"/>
  <variable name="x_6_0" index="96" value="1.00000"/>
  <variable name="x_7_5" index="117" value="1.00000"/>
  <variable name="x_8_0" index="128" value="1.00000"/>
  <variable name="x_9_0" index="144" value="1.00000"/>
  <variable name="x_10_9" index="169" value="1.00000"/>
  <variable name="x_11_0" index="176" value="1.00000"/>
  <variable name="x_12_10" index="202" value="1.00000"/>
  <variable name="x_13_14" index="221" value="1.00000"/>
  <variable name="x_14_0" index="224" value="1.00000"/>
  <variable name="x_15_11" index="251" value="1.00000"/>
  <variable name="x_16_0" index="256" value="1.00000"/>
  <variable name="u_1" index="272" value="18.00000"/>
  <variable name="u_2" index="273" value="25.00000"/>
  <variable name="u_3" index="274" value="22.00000"/>
  <variable name="u_4" index="275" value="12.00000"/>
  <variable name="u_5" index="276" value="18.00000"/>
  <variable name="u_6" index="277" value="24.00000"/>
  <variable name="u_7" index="278" value="7.00000"/>
  <variable name="u_8" index="279" value="26.00000"/>
  <variable name="u_9" index="280" value="26.00000"/>
  <variable name="u_10" index="281" value="22.00000"/>
  <variable name="u_11" index="282" value="25.00000"/>
  <variable name="u_12" index="283" value="8.00000"/>
  <variable name="u_13" index="284" value="21.00000"/>
  <variable name="u_14" index="285" value="26.00000"/>
  <variable name="u_15" index="286" value="21.00000"/>
  <variable name="u_16" index="287" value="26.00000"/>
 </variables>
</CPLEXSolution>
