<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="9044.63"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_1_0" index="15" value="1.00000"/>
  <variable name="x_2_12" index="41" value="1.00000"/>
  <variable name="x_3_0" index="45" value="1.00000"/>
  <variable name="x_4_0" index="60" value="1.00000"/>
  <variable name="x_5_8" index="82" value="1.00000"/>
  <variable name="x_6_0" index="90" value="1.00000"/>
  <variable name="x_7_0" index="105" value="1.00000"/>
  <variable name="x_8_13" index="132" value="1.00000"/>
  <variable name="x_9_0" index="135" value="1.00000"/>
  <variable name="x_10_4" index="154" value="1.00000"/>
  <variable name="x_11_0" index="165" value="1.00000"/>
  <variable name="x_12_9" index="189" value="1.00000"/>
  <variable name="x_13_14" index="208" value="1.00000"/>
  <variable name="x_14_0" index="210" value="1.00000"/>
  <variable name="x_15_3" index="228" value="1.00000"/>
  <variable name="u_1" index="240" value="36.00000"/>
  <variable name="u_2" index="241" value="3.00000"/>
  <variable name="u_3" index="242" value="37.00000"/>
  <variable name="u_4" index="243" value="39.00000"/>
  <variable name="u_5" index="244" value="3.00000"/>
  <variable name="u_6" index="245" value="36.00000"/>
  <variable name="u_7" index="246" value="34.00000"/>
  <variable name="u_8" index="247" value="12.00000"/>
  <variable name="u_9" index="248" value="34.00000"/>
  <variable name="u_10" index="249" value="31.00000"/>
  <variable name="u_11" index="250" value="34.00000"/>
  <variable name="u_12" index="251" value="13.00000"/>
  <variable name="u_13" index="252" value="34.00000"/>
  <variable name="u_14" index="253" value="39.00000"/>
  <variable name="u_15" index="254" value="3.00000"/>
 </variables>
</CPLEXSolution>
