<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="17872.6"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_1_0" index="23" value="1.00000"/>
  <variable name="x_2_21" index="66" value="1.00000"/>
  <variable name="x_3_0" index="69" value="1.00000"/>
  <variable name="x_4_6" index="97" value="1.00000"/>
  <variable name="x_5_17" index="131" value="1.00000"/>
  <variable name="x_6_0" index="138" value="1.00000"/>
  <variable name="x_7_23" index="183" value="1.00000"/>
  <variable name="x_8_0" index="184" value="1.00000"/>
  <variable name="x_9_12" index="218" value="1.00000"/>
  <variable name="x_10_22" index="251" value="1.00000"/>
  <variable name="x_11_10" index="263" value="1.00000"/>
  <variable name="x_12_0" index="276" value="1.00000"/>
  <variable name="x_13_0" index="299" value="1.00000"/>
  <variable name="x_14_3" index="325" value="1.00000"/>
  <variable name="x_15_0" index="345" value="1.00000"/>
  <variable name="x_16_0" index="368" value="1.00000"/>
  <variable name="x_17_0" index="391" value="1.00000"/>
  <variable name="x_18_7" index="421" value="1.00000"/>
  <variable name="x_19_16" index="453" value="1.00000"/>
  <variable name="x_20_0" index="460" value="1.00000"/>
  <variable name="x_21_1" index="484" value="1.00000"/>
  <variable name="x_22_0" index="506" value="1.00000"/>
  <variable name="x_23_0" index="529" value="1.00000"/>
  <variable name="u_1" index="552" value="39.00000"/>
  <variable name="u_2" index="553" value="2.00000"/>
  <variable name="u_3" index="554" value="37.00000"/>
  <variable name="u_4" index="555" value="23.00000"/>
  <variable name="u_5" index="556" value="26.00000"/>
  <variable name="u_6" index="557" value="37.00000"/>
  <variable name="u_7" index="558" value="23.00000"/>
  <variable name="u_8" index="559" value="35.00000"/>
  <variable name="u_9" index="560" value="19.00000"/>
  <variable name="u_10" index="561" value="35.00000"/>
  <variable name="u_11" index="562" value="11.00000"/>
  <variable name="u_12" index="563" value="36.00000"/>
  <variable name="u_13" index="564" value="39.00000"/>
  <variable name="u_14" index="565" value="13.00000"/>
  <variable name="u_15" index="566" value="25.00000"/>
  <variable name="u_16" index="567" value="35.00000"/>
  <variable name="u_17" index="568" value="37.00000"/>
  <variable name="u_18" index="569" value="17.00000"/>
  <variable name="u_19" index="570" value="27.00000"/>
  <variable name="u_20" index="571" value="39.00000"/>
  <variable name="u_21" index="572" value="33.00000"/>
  <variable name="u_22" index="573" value="39.00000"/>
  <variable name="u_23" index="574" value="39.00000"/>
 </variables>
</CPLEXSolution>
