<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="8853.85"
  />
 <variables>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_1_0" index="11" value="1.00000"/>
  <variable name="x_2_1" index="23" value="1.00000"/>
  <variable name="x_3_0" index="33" value="1.00000"/>
  <variable name="x_4_0" index="44" value="1.00000"/>
  <variable name="x_5_0" index="55" value="1.00000"/>
  <variable name="x_6_8" index="73" value="1.00000"/>
  <variable name="x_7_0" index="77" value="1.00000"/>
  <variable name="x_8_11" index="98" value="1.00000"/>
  <variable name="x_9_3" index="102" value="1.00000"/>
  <variable name="x_10_2" index="112" value="1.00000"/>
  <variable name="x_11_0" index="121" value="1.00000"/>
  <variable name="u_1" index="132" value="67.00000"/>
  <variable name="u_2" index="133" value="22.00000"/>
  <variable name="u_3" index="134" value="66.00000"/>
  <variable name="u_4" index="135" value="51.00000"/>
  <variable name="u_5" index="136" value="73.00000"/>
  <variable name="u_6" index="137" value="33.00000"/>
  <variable name="u_7" index="138" value="72.00000"/>
  <variable name="u_8" index="139" value="59.00000"/>
  <variable name="u_9" index="140" value="54.00000"/>
  <variable name="u_10" index="141" value="21.00000"/>
  <variable name="u_11" index="142" value="73.00000"/>
 </variables>
</CPLEXSolution>
