<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="7056.64"
  />
 <variables>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_1_0" index="13" value="1.00000"/>
  <variable name="x_2_0" index="26" value="1.00000"/>
  <variable name="x_3_2" index="41" value="1.00000"/>
  <variable name="x_4_0" index="52" value="1.00000"/>
  <variable name="x_5_1" index="66" value="1.00000"/>
  <variable name="x_6_0" index="78" value="1.00000"/>
  <variable name="x_7_4" index="95" value="1.00000"/>
  <variable name="x_8_0" index="104" value="1.00000"/>
  <variable name="x_9_6" index="123" value="1.00000"/>
  <variable name="x_10_9" index="139" value="1.00000"/>
  <variable name="x_11_0" index="143" value="1.00000"/>
  <variable name="x_12_8" index="164" value="1.00000"/>
  <variable name="x_13_0" index="169" value="1.00000"/>
  <variable name="u_1" index="182" value="47.00000"/>
  <variable name="u_2" index="183" value="49.00000"/>
  <variable name="u_3" index="184" value="37.00000"/>
  <variable name="u_4" index="185" value="58.00000"/>
  <variable name="u_5" index="186" value="16.00000"/>
  <variable name="u_6" index="187" value="45.00000"/>
  <variable name="u_7" index="188" value="52.00000"/>
  <variable name="u_8" index="189" value="58.00000"/>
  <variable name="u_9" index="190" value="38.00000"/>
  <variable name="u_10" index="191" value="11.00000"/>
  <variable name="u_11" index="192" value="41.00000"/>
  <variable name="u_12" index="193" value="21.00000"/>
  <variable name="u_13" index="194" value="38.00000"/>
 </variables>
</CPLEXSolution>
