<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="10648.9"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_1_14" index="32" value="1.00000"/>
  <variable name="x_2_0" index="38" value="1.00000"/>
  <variable name="x_3_9" index="65" value="1.00000"/>
  <variable name="x_4_0" index="76" value="1.00000"/>
  <variable name="x_5_4" index="99" value="1.00000"/>
  <variable name="x_6_0" index="114" value="1.00000"/>
  <variable name="x_7_13" index="145" value="1.00000"/>
  <variable name="x_8_0" index="152" value="1.00000"/>
  <variable name="x_9_0" index="171" value="1.00000"/>
  <variable name="x_10_17" index="206" value="1.00000"/>
  <variable name="x_11_0" index="209" value="1.00000"/>
  <variable name="x_12_0" index="228" value="1.00000"/>
  <variable name="x_13_0" index="247" value="1.00000"/>
  <variable name="x_14_0" index="266" value="1.00000"/>
  <variable name="x_15_19" index="303" value="1.00000"/>
  <variable name="x_16_12" index="316" value="1.00000"/>
  <variable name="x_17_0" index="323" value="1.00000"/>
  <variable name="x_18_2" index="344" value="1.00000"/>
  <variable name="x_19_5" index="366" value="1.00000"/>
  <variable name="u_1" index="380" value="6.00000"/>
  <variable name="u_2" index="381" value="52.00000"/>
  <variable name="u_3" index="382" value="34.00000"/>
  <variable name="u_4" index="383" value="52.00000"/>
  <variable name="u_5" index="384" value="25.00000"/>
  <variable name="u_6" index="385" value="50.00000"/>
  <variable name="u_7" index="386" value="44.00000"/>
  <variable name="u_8" index="387" value="50.00000"/>
  <variable name="u_9" index="388" value="52.00000"/>
  <variable name="u_10" index="389" value="39.00000"/>
  <variable name="u_11" index="390" value="52.00000"/>
  <variable name="u_12" index="391" value="52.00000"/>
  <variable name="u_13" index="392" value="52.00000"/>
  <variable name="u_14" index="393" value="40.00000"/>
  <variable name="u_15" index="394" value="16.00000"/>
  <variable name="u_16" index="395" value="30.00000"/>
  <variable name="u_17" index="396" value="52.00000"/>
  <variable name="u_18" index="397" value="14.00000"/>
  <variable name="u_19" index="398" value="22.00000"/>
 </variables>
</CPLEXSolution>
