<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="7926.6"
  />
 <variables>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_1_3" index="21" value="1.00000"/>
  <variable name="x_2_17" index="54" value="1.00000"/>
  <variable name="x_3_0" index="57" value="1.00000"/>
  <variable name="x_4_10" index="85" value="1.00000"/>
  <variable name="x_5_2" index="97" value="1.00000"/>
  <variable name="x_6_0" index="114" value="1.00000"/>
  <variable name="x_7_0" index="133" value="1.00000"/>
  <variable name="x_8_0" index="152" value="1.00000"/>
  <variable name="x_9_0" index="171" value="1.00000"/>
  <variable name="x_10_0" index="190" value="1.00000"/>
  <variable name="x_11_18" index="226" value="1.00000"/>
  <variable name="x_12_4" index="232" value="1.00000"/>
  <variable name="x_13_16" index="262" value="1.00000"/>
  <variable name="x_14_8" index="274" value="1.00000"/>
  <variable name="x_15_7" index="292" value="1.00000"/>
  <variable name="x_16_0" index="304" value="1.00000"/>
  <variable name="x_17_0" index="323" value="1.00000"/>
  <variable name="x_18_19" index="360" value="1.00000"/>
  <variable name="x_19_1" index="362" value="1.00000"/>
  <variable name="u_1" index="380" value="76.00000"/>
  <variable name="u_2" index="381" value="44.00000"/>
  <variable name="u_3" index="382" value="79.00000"/>
  <variable name="u_4" index="383" value="66.00000"/>
  <variable name="u_5" index="384" value="22.00000"/>
  <variable name="u_6" index="385" value="76.00000"/>
  <variable name="u_7" index="386" value="79.00000"/>
  <variable name="u_8" index="387" value="79.00000"/>
  <variable name="u_9" index="388" value="55.00000"/>
  <variable name="u_10" index="389" value="79.00000"/>
  <variable name="u_11" index="390" value="25.00000"/>
  <variable name="u_12" index="391" value="33.00000"/>
  <variable name="u_13" index="392" value="54.00000"/>
  <variable name="u_14" index="393" value="76.00000"/>
  <variable name="u_15" index="394" value="65.00000"/>
  <variable name="u_16" index="395" value="79.00000"/>
  <variable name="u_17" index="396" value="61.00000"/>
  <variable name="u_18" index="397" value="39.00000"/>
  <variable name="u_19" index="398" value="51.00000"/>
 </variables>
</CPLEXSolution>
