<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="13477.1"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_0_22" index="21" value="1.00000"/>
  <variable name="x_1_0" index="23" value="1.00000"/>
  <variable name="x_2_15" index="60" value="1.00000"/>
  <variable name="x_3_4" index="72" value="1.00000"/>
  <variable name="x_4_6" index="97" value="1.00000"/>
  <variable name="x_5_12" index="126" value="1.00000"/>
  <variable name="x_6_0" index="138" value="1.00000"/>
  <variable name="x_7_0" index="161" value="1.00000"/>
  <variable name="x_8_0" index="184" value="1.00000"/>
  <variable name="x_9_0" index="207" value="1.00000"/>
  <variable name="x_10_0" index="230" value="1.00000"/>
  <variable name="x_11_9" index="262" value="1.00000"/>
  <variable name="x_12_0" index="276" value="1.00000"/>
  <variable name="x_13_0" index="299" value="1.00000"/>
  <variable name="x_14_0" index="322" value="1.00000"/>
  <variable name="x_15_23" index="367" value="1.00000"/>
  <variable name="x_16_0" index="368" value="1.00000"/>
  <variable name="x_17_21" index="411" value="1.00000"/>
  <variable name="x_18_20" index="433" value="1.00000"/>
  <variable name="x_19_3" index="440" value="1.00000"/>
  <variable name="x_20_0" index="460" value="1.00000"/>
  <variable name="x_21_0" index="483" value="1.00000"/>
  <variable name="x_22_13" index="519" value="1.00000"/>
  <variable name="x_23_0" index="529" value="1.00000"/>
  <variable name="u_1" index="552" value="41.00000"/>
  <variable name="u_2" index="553" value="17.00000"/>
  <variable name="u_3" index="554" value="34.00000"/>
  <variable name="u_4" index="555" value="49.00000"/>
  <variable name="u_5" index="556" value="30.00000"/>
  <variable name="u_6" index="557" value="50.00000"/>
  <variable name="u_7" index="558" value="50.00000"/>
  <variable name="u_8" index="559" value="38.00000"/>
  <variable name="u_9" index="560" value="50.00000"/>
  <variable name="u_10" index="561" value="50.00000"/>
  <variable name="u_11" index="562" value="15.00000"/>
  <variable name="u_12" index="563" value="46.00000"/>
  <variable name="u_13" index="564" value="43.00000"/>
  <variable name="u_14" index="565" value="48.00000"/>
  <variable name="u_15" index="566" value="32.00000"/>
  <variable name="u_16" index="567" value="41.00000"/>
  <variable name="u_17" index="568" value="32.00000"/>
  <variable name="u_18" index="569" value="27.00000"/>
  <variable name="u_19" index="570" value="14.00000"/>
  <variable name="u_20" index="571" value="50.00000"/>
  <variable name="u_21" index="572" value="48.00000"/>
  <variable name="u_22" index="573" value="40.00000"/>
  <variable name="u_23" index="574" value="47.00000"/>
 </variables>
</CPLEXSolution>
