<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="11607.6"
  />
 <variables>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_1_0" index="19" value="1.00000"/>
  <variable name="x_2_3" index="40" value="1.00000"/>
  <variable name="x_3_0" index="57" value="1.00000"/>
  <variable name="x_4_0" index="76" value="1.00000"/>
  <variable name="x_5_0" index="95" value="1.00000"/>
  <variable name="x_6_0" index="114" value="1.00000"/>
  <variable name="x_7_12" index="144" value="1.00000"/>
  <variable name="x_8_1" index="153" value="1.00000"/>
  <variable name="x_9_5" index="176" value="1.00000"/>
  <variable name="x_10_11" index="200" value="1.00000"/>
  <variable name="x_11_17" index="225" value="1.00000"/>
  <variable name="x_12_0" index="228" value="1.00000"/>
  <variable name="x_13_0" index="247" value="1.00000"/>
  <variable name="x_14_2" index="268" value="1.00000"/>
  <variable name="x_15_0" index="285" value="1.00000"/>
  <variable name="x_16_0" index="304" value="1.00000"/>
  <variable name="x_17_0" index="323" value="1.00000"/>
  <variable name="x_18_8" index="350" value="1.00000"/>
  <variable name="x_19_9" index="370" value="1.00000"/>
  <variable name="u_1" index="380" value="43.00000"/>
  <variable name="u_2" index="381" value="11.00000"/>
  <variable name="u_3" index="382" value="43.00000"/>
  <variable name="u_4" index="383" value="43.00000"/>
  <variable name="u_5" index="384" value="43.00000"/>
  <variable name="u_6" index="385" value="32.00000"/>
  <variable name="u_7" index="386" value="30.00000"/>
  <variable name="u_8" index="387" value="30.00000"/>
  <variable name="u_9" index="388" value="23.00000"/>
  <variable name="u_10" index="389" value="23.00000"/>
  <variable name="u_11" index="390" value="41.00000"/>
  <variable name="u_12" index="391" value="34.00000"/>
  <variable name="u_13" index="392" value="40.00000"/>
  <variable name="u_14" index="393" value="5.00000"/>
  <variable name="u_15" index="394" value="38.00000"/>
  <variable name="u_16" index="395" value="31.00000"/>
  <variable name="u_17" index="396" value="43.00000"/>
  <variable name="u_18" index="397" value="23.00000"/>
  <variable name="u_19" index="398" value="6.00000"/>
 </variables>
</CPLEXSolution>
