<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="8165.45"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_1_8" index="18" value="1.00000"/>
  <variable name="x_2_5" index="26" value="1.00000"/>
  <variable name="x_3_0" index="33" value="1.00000"/>
  <variable name="x_4_7" index="50" value="1.00000"/>
  <variable name="x_5_0" index="55" value="1.00000"/>
  <variable name="x_6_0" index="66" value="1.00000"/>
  <variable name="x_7_9" index="85" value="1.00000"/>
  <variable name="x_8_0" index="88" value="1.00000"/>
  <variable name="x_9_0" index="99" value="1.00000"/>
  <variable name="x_10_2" index="112" value="1.00000"/>
  <variable name="x_11_0" index="121" value="1.00000"/>
  <variable name="u_1" index="132" value="10.00000"/>
  <variable name="u_2" index="133" value="25.00000"/>
  <variable name="u_3" index="134" value="37.00000"/>
  <variable name="u_4" index="135" value="10.00000"/>
  <variable name="u_5" index="136" value="37.00000"/>
  <variable name="u_6" index="137" value="30.00000"/>
  <variable name="u_7" index="138" value="25.00000"/>
  <variable name="u_8" index="139" value="35.00000"/>
  <variable name="u_9" index="140" value="37.00000"/>
  <variable name="u_10" index="141" value="23.00000"/>
  <variable name="u_11" index="142" value="30.00000"/>
 </variables>
</CPLEXSolution>
