<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="14883"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_0_21" index="20" value="1.00000"/>
  <variable name="x_1_0" index="21" value="1.00000"/>
  <variable name="x_2_0" index="42" value="1.00000"/>
  <variable name="x_3_0" index="63" value="1.00000"/>
  <variable name="x_4_10" index="93" value="1.00000"/>
  <variable name="x_5_0" index="105" value="1.00000"/>
  <variable name="x_6_0" index="126" value="1.00000"/>
  <variable name="x_7_15" index="161" value="1.00000"/>
  <variable name="x_8_0" index="168" value="1.00000"/>
  <variable name="x_9_2" index="191" value="1.00000"/>
  <variable name="x_10_0" index="210" value="1.00000"/>
  <variable name="x_11_18" index="248" value="1.00000"/>
  <variable name="x_12_0" index="252" value="1.00000"/>
  <variable name="x_13_0" index="273" value="1.00000"/>
  <variable name="x_14_0" index="294" value="1.00000"/>
  <variable name="x_15_0" index="315" value="1.00000"/>
  <variable name="x_16_5" index="341" value="1.00000"/>
  <variable name="x_17_16" index="373" value="1.00000"/>
  <variable name="x_18_0" index="378" value="1.00000"/>
  <variable name="x_19_6" index="405" value="1.00000"/>
  <variable name="x_20_19" index="439" value="1.00000"/>
  <variable name="x_21_0" index="441" value="1.00000"/>
  <variable name="u_1" index="462" value="47.00000"/>
  <variable name="u_2" index="463" value="63.00000"/>
  <variable name="u_3" index="464" value="61.00000"/>
  <variable name="u_4" index="465" value="7.00000"/>
  <variable name="u_5" index="466" value="51.00000"/>
  <variable name="u_6" index="467" value="63.00000"/>
  <variable name="u_7" index="468" value="30.00000"/>
  <variable name="u_8" index="469" value="64.00000"/>
  <variable name="u_9" index="470" value="26.00000"/>
  <variable name="u_10" index="471" value="51.00000"/>
  <variable name="u_11" index="472" value="8.00000"/>
  <variable name="u_12" index="473" value="33.00000"/>
  <variable name="u_13" index="474" value="54.00000"/>
  <variable name="u_14" index="475" value="63.00000"/>
  <variable name="u_15" index="476" value="62.00000"/>
  <variable name="u_16" index="477" value="40.00000"/>
  <variable name="u_17" index="478" value="8.00000"/>
  <variable name="u_18" index="479" value="51.00000"/>
  <variable name="u_19" index="480" value="44.00000"/>
  <variable name="u_20" index="481" value="33.00000"/>
  <variable name="u_21" index="482" value="58.00000"/>
 </variables>
</CPLEXSolution>
