<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="11544.7"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_1_14" index="27" value="1.00000"/>
  <variable name="x_2_0" index="28" value="1.00000"/>
  <variable name="x_3_0" index="42" value="1.00000"/>
  <variable name="x_4_10" index="65" value="1.00000"/>
  <variable name="x_5_0" index="70" value="1.00000"/>
  <variable name="x_6_0" index="84" value="1.00000"/>
  <variable name="x_7_13" index="110" value="1.00000"/>
  <variable name="x_8_0" index="112" value="1.00000"/>
  <variable name="x_9_0" index="126" value="1.00000"/>
  <variable name="x_10_0" index="140" value="1.00000"/>
  <variable name="x_11_0" index="154" value="1.00000"/>
  <variable name="x_12_3" index="171" value="1.00000"/>
  <variable name="x_13_0" index="182" value="1.00000"/>
  <variable name="x_14_9" index="205" value="1.00000"/>
  <variable name="u_1" index="210" value="7.00000"/>
  <variable name="u_2" index="211" value="35.00000"/>
  <variable name="u_3" index="212" value="41.00000"/>
  <variable name="u_4" index="213" value="36.00000"/>
  <variable name="u_5" index="214" value="29.00000"/>
  <variable name="u_6" index="215" value="28.00000"/>
  <variable name="u_7" index="216" value="23.00000"/>
  <variable name="u_8" index="217" value="37.00000"/>
  <variable name="u_9" index="218" value="42.00000"/>
  <variable name="u_10" index="219" value="40.00000"/>
  <variable name="u_11" index="220" value="42.00000"/>
  <variable name="u_12" index="221" value="40.00000"/>
  <variable name="u_13" index="222" value="35.00000"/>
  <variable name="u_14" index="223" value="33.00000"/>
 </variables>
</CPLEXSolution>
