<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="11526.2"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_1_7" index="21" value="1.00000"/>
  <variable name="x_2_5" index="34" value="1.00000"/>
  <variable name="x_3_6" index="50" value="1.00000"/>
  <variable name="x_4_0" index="60" value="1.00000"/>
  <variable name="x_5_0" index="75" value="1.00000"/>
  <variable name="x_6_0" index="90" value="1.00000"/>
  <variable name="x_7_2" index="107" value="1.00000"/>
  <variable name="x_8_0" index="120" value="1.00000"/>
  <variable name="x_9_0" index="135" value="1.00000"/>
  <variable name="x_10_4" index="154" value="1.00000"/>
  <variable name="x_11_0" index="165" value="1.00000"/>
  <variable name="x_12_0" index="180" value="1.00000"/>
  <variable name="x_13_0" index="195" value="1.00000"/>
  <variable name="x_14_0" index="210" value="1.00000"/>
  <variable name="x_15_14" index="239" value="1.00000"/>
  <variable name="u_1" index="240" value="8.00000"/>
  <variable name="u_2" index="241" value="49.00000"/>
  <variable name="u_3" index="242" value="16.00000"/>
  <variable name="u_4" index="243" value="59.00000"/>
  <variable name="u_5" index="244" value="69.00000"/>
  <variable name="u_6" index="245" value="69.00000"/>
  <variable name="u_7" index="246" value="14.00000"/>
  <variable name="u_8" index="247" value="68.00000"/>
  <variable name="u_9" index="248" value="59.00000"/>
  <variable name="u_10" index="249" value="44.00000"/>
  <variable name="u_11" index="250" value="28.00000"/>
  <variable name="u_12" index="251" value="69.00000"/>
  <variable name="u_13" index="252" value="67.00000"/>
  <variable name="u_14" index="253" value="69.00000"/>
  <variable name="u_15" index="254" value="30.00000"/>
 </variables>
</CPLEXSolution>
