<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="21290.1"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_0_21" index="20" value="1.00000"/>
  <variable name="x_0_22" index="21" value="1.00000"/>
  <variable name="x_0_23" index="22" value="1.00000"/>
  <variable name="x_0_25" index="24" value="1.00000"/>
  <variable name="x_0_26" index="25" value="1.00000"/>
  <variable name="x_1_0" index="26" value="1.00000"/>
  <variable name="x_2_0" index="52" value="1.00000"/>
  <variable name="x_3_0" index="78" value="1.00000"/>
  <variable name="x_4_0" index="104" value="1.00000"/>
  <variable name="x_5_0" index="130" value="1.00000"/>
  <variable name="x_6_2" index="158" value="1.00000"/>
  <variable name="x_7_0" index="182" value="1.00000"/>
  <variable name="x_8_0" index="208" value="1.00000"/>
  <variable name="x_9_18" index="251" value="1.00000"/>
  <variable name="x_10_0" index="260" value="1.00000"/>
  <variable name="x_11_0" index="286" value="1.00000"/>
  <variable name="x_12_0" index="312" value="1.00000"/>
  <variable name="x_13_24" index="361" value="1.00000"/>
  <variable name="x_14_0" index="364" value="1.00000"/>
  <variable name="x_15_19" index="408" value="1.00000"/>
  <variable name="x_16_3" index="419" value="1.00000"/>
  <variable name="x_17_0" index="442" value="1.00000"/>
  <variable name="x_18_0" index="468" value="1.00000"/>
  <variable name="x_19_6" index="500" value="1.00000"/>
  <variable name="x_20_0" index="520" value="1.00000"/>
  <variable name="x_21_0" index="546" value="1.00000"/>
  <variable name="x_22_7" index="579" value="1.00000"/>
  <variable name="x_23_10" index="608" value="1.00000"/>
  <variable name="x_24_0" index="624" value="1.00000"/>
  <variable name="x_25_0" index="650" value="1.00000"/>
  <variable name="x_26_0" index="676" value="1.00000"/>
  <variable name="u_1" index="702" value="35.00000"/>
  <variable name="u_2" index="703" value="41.00000"/>
  <variable name="u_3" index="704" value="33.00000"/>
  <variable name="u_4" index="705" value="41.00000"/>
  <variable name="u_5" index="706" value="34.00000"/>
  <variable name="u_6" index="707" value="39.00000"/>
  <variable name="u_7" index="708" value="41.00000"/>
  <variable name="u_8" index="709" value="31.00000"/>
  <variable name="u_9" index="710" value="7.00000"/>
  <variable name="u_10" index="711" value="32.00000"/>
  <variable name="u_11" index="712" value="29.00000"/>
  <variable name="u_12" index="713" value="37.00000"/>
  <variable name="u_13" index="714" value="32.00000"/>
  <variable name="u_14" index="715" value="36.00000"/>
  <variable name="u_15" index="716" value="19.00000"/>
  <variable name="u_16" index="717" value="9.00000"/>
  <variable name="u_17" index="718" value="38.00000"/>
  <variable name="u_18" index="719" value="41.00000"/>
  <variable name="u_19" index="720" value="36.00000"/>
  <variable name="u_20" index="721" value="41.00000"/>
  <variable name="u_21" index="722" value="41.00000"/>
  <variable name="u_22" index="723" value="28.00000"/>
  <variable name="u_23" index="724" value="8.00000"/>
  <variable name="u_24" index="725" value="41.00000"/>
  <variable name="u_25" index="726" value="22.00000"/>
  <variable name="u_26" index="727" value="37.00000"/>
 </variables>
</CPLEXSolution>
