<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="16487.2"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_0_21" index="20" value="1.00000"/>
  <variable name="x_0_23" index="22" value="1.00000"/>
  <variable name="x_0_25" index="24" value="1.00000"/>
  <variable name="x_0_26" index="25" value="1.00000"/>
  <variable name="x_1_28" index="55" value="1.00000"/>
  <variable name="x_2_10" index="65" value="1.00000"/>
  <variable name="x_3_18" index="101" value="1.00000"/>
  <variable name="x_4_0" index="112" value="1.00000"/>
  <variable name="x_5_0" index="140" value="1.00000"/>
  <variable name="x_6_0" index="168" value="1.00000"/>
  <variable name="x_7_0" index="196" value="1.00000"/>
  <variable name="x_8_1" index="225" value="1.00000"/>
  <variable name="x_9_0" index="252" value="1.00000"/>
  <variable name="x_10_0" index="280" value="1.00000"/>
  <variable name="x_11_22" index="329" value="1.00000"/>
  <variable name="x_12_24" index="359" value="1.00000"/>
  <variable name="x_13_4" index="368" value="1.00000"/>
  <variable name="x_14_0" index="392" value="1.00000"/>
  <variable name="x_15_0" index="420" value="1.00000"/>
  <variable name="x_16_12" index="460" value="1.00000"/>
  <variable name="x_17_0" index="476" value="1.00000"/>
  <variable name="x_18_0" index="504" value="1.00000"/>
  <variable name="x_19_0" index="532" value="1.00000"/>
  <variable name="x_20_0" index="560" value="1.00000"/>
  <variable name="x_21_27" index="614" value="1.00000"/>
  <variable name="x_22_0" index="616" value="1.00000"/>
  <variable name="x_23_0" index="644" value="1.00000"/>
  <variable name="x_24_7" index="679" value="1.00000"/>
  <variable name="x_25_0" index="700" value="1.00000"/>
  <variable name="x_26_0" index="728" value="1.00000"/>
  <variable name="x_27_0" index="756" value="1.00000"/>
  <variable name="x_28_9" index="793" value="1.00000"/>
  <variable name="u_1" index="812" value="15.00000"/>
  <variable name="u_2" index="813" value="18.00000"/>
  <variable name="u_3" index="814" value="53.00000"/>
  <variable name="u_4" index="815" value="56.00000"/>
  <variable name="u_5" index="816" value="56.00000"/>
  <variable name="u_6" index="817" value="50.00000"/>
  <variable name="u_7" index="818" value="56.00000"/>
  <variable name="u_8" index="819" value="1.00000"/>
  <variable name="u_9" index="820" value="56.00000"/>
  <variable name="u_10" index="821" value="56.00000"/>
  <variable name="u_11" index="822" value="28.00000"/>
  <variable name="u_12" index="823" value="23.00000"/>
  <variable name="u_13" index="824" value="20.00000"/>
  <variable name="u_14" index="825" value="49.00000"/>
  <variable name="u_15" index="826" value="38.00000"/>
  <variable name="u_16" index="827" value="19.00000"/>
  <variable name="u_17" index="828" value="44.00000"/>
  <variable name="u_18" index="829" value="56.00000"/>
  <variable name="u_19" index="830" value="56.00000"/>
  <variable name="u_20" index="831" value="46.00000"/>
  <variable name="u_21" index="832" value="31.00000"/>
  <variable name="u_22" index="833" value="54.00000"/>
  <variable name="u_23" index="834" value="54.00000"/>
  <variable name="u_24" index="835" value="43.00000"/>
  <variable name="u_25" index="836" value="53.00000"/>
  <variable name="u_26" index="837" value="56.00000"/>
  <variable name="u_27" index="838" value="52.00000"/>
  <variable name="u_28" index="839" value="55.00000"/>
 </variables>
</CPLEXSolution>
