<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="10963"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_13" index="12" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_1_0" index="16" value="1.00000"/>
  <variable name="x_2_12" index="43" value="1.00000"/>
  <variable name="x_3_0" index="48" value="1.00000"/>
  <variable name="x_4_0" index="64" value="1.00000"/>
  <variable name="x_5_0" index="80" value="1.00000"/>
  <variable name="x_6_0" index="96" value="1.00000"/>
  <variable name="x_7_1" index="113" value="1.00000"/>
  <variable name="x_8_7" index="135" value="1.00000"/>
  <variable name="x_9_15" index="158" value="1.00000"/>
  <variable name="x_10_6" index="166" value="1.00000"/>
  <variable name="x_11_0" index="176" value="1.00000"/>
  <variable name="x_12_0" index="192" value="1.00000"/>
  <variable name="x_13_0" index="208" value="1.00000"/>
  <variable name="x_14_0" index="224" value="1.00000"/>
  <variable name="x_15_0" index="240" value="1.00000"/>
  <variable name="x_16_4" index="260" value="1.00000"/>
  <variable name="u_1" index="272" value="67.00000"/>
  <variable name="u_2" index="273" value="52.00000"/>
  <variable name="u_3" index="274" value="75.00000"/>
  <variable name="u_4" index="275" value="72.00000"/>
  <variable name="u_5" index="276" value="42.00000"/>
  <variable name="u_6" index="277" value="62.00000"/>
  <variable name="u_7" index="278" value="63.00000"/>
  <variable name="u_8" index="279" value="5.00000"/>
  <variable name="u_9" index="280" value="41.00000"/>
  <variable name="u_10" index="281" value="47.00000"/>
  <variable name="u_11" index="282" value="75.00000"/>
  <variable name="u_12" index="283" value="71.00000"/>
  <variable name="u_13" index="284" value="67.00000"/>
  <variable name="u_14" index="285" value="68.00000"/>
  <variable name="u_15" index="286" value="65.00000"/>
  <variable name="u_16" index="287" value="42.00000"/>
 </variables>
</CPLEXSolution>
