<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="14715.4"
  />
 <variables>
  <variable name="x_0_1" index="0" value="1.00000"/>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_8" index="7" value="1.00000"/>
  <variable name="x_0_9" index="8" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_19" index="18" value="1.00000"/>
  <variable name="x_0_23" index="22" value="1.00000"/>
  <variable name="x_0_26" index="25" value="1.00000"/>
  <variable name="x_1_5" index="30" value="1.00000"/>
  <variable name="x_2_0" index="52" value="1.00000"/>
  <variable name="x_3_0" index="78" value="1.00000"/>
  <variable name="x_4_0" index="104" value="1.00000"/>
  <variable name="x_5_0" index="130" value="1.00000"/>
  <variable name="x_6_20" index="175" value="1.00000"/>
  <variable name="x_7_0" index="182" value="1.00000"/>
  <variable name="x_8_18" index="225" value="1.00000"/>
  <variable name="x_9_4" index="238" value="1.00000"/>
  <variable name="x_10_22" index="281" value="1.00000"/>
  <variable name="x_11_0" index="286" value="1.00000"/>
  <variable name="x_12_0" index="312" value="1.00000"/>
  <variable name="x_13_0" index="338" value="1.00000"/>
  <variable name="x_14_7" index="371" value="1.00000"/>
  <variable name="x_15_0" index="390" value="1.00000"/>
  <variable name="x_16_13" index="429" value="1.00000"/>
  <variable name="x_17_24" index="465" value="1.00000"/>
  <variable name="x_18_0" index="468" value="1.00000"/>
  <variable name="x_19_21" index="514" value="1.00000"/>
  <variable name="x_20_0" index="520" value="1.00000"/>
  <variable name="x_21_0" index="546" value="1.00000"/>
  <variable name="x_22_0" index="572" value="1.00000"/>
  <variable name="x_23_0" index="598" value="1.00000"/>
  <variable name="x_24_0" index="624" value="1.00000"/>
  <variable name="x_25_12" index="662" value="1.00000"/>
  <variable name="x_26_25" index="701" value="1.00000"/>
  <variable name="u_1" index="702" value="22.00000"/>
  <variable name="u_2" index="703" value="44.00000"/>
  <variable name="u_3" index="704" value="45.00000"/>
  <variable name="u_4" index="705" value="43.00000"/>
  <variable name="u_5" index="706" value="51.00000"/>
  <variable name="u_6" index="707" value="34.00000"/>
  <variable name="u_7" index="708" value="50.00000"/>
  <variable name="u_8" index="709" value="12.00000"/>
  <variable name="u_9" index="710" value="19.00000"/>
  <variable name="u_10" index="711" value="31.00000"/>
  <variable name="u_11" index="712" value="46.00000"/>
  <variable name="u_12" index="713" value="49.00000"/>
  <variable name="u_13" index="714" value="48.00000"/>
  <variable name="u_14" index="715" value="35.00000"/>
  <variable name="u_15" index="716" value="51.00000"/>
  <variable name="u_16" index="717" value="10.00000"/>
  <variable name="u_17" index="718" value="46.00000"/>
  <variable name="u_18" index="719" value="49.00000"/>
  <variable name="u_19" index="720" value="5.00000"/>
  <variable name="u_20" index="721" value="51.00000"/>
  <variable name="u_21" index="722" value="35.00000"/>
  <variable name="u_22" index="723" value="51.00000"/>
  <variable name="u_23" index="724" value="51.00000"/>
  <variable name="u_24" index="725" value="51.00000"/>
  <variable name="u_25" index="726" value="47.00000"/>
  <variable name="u_26" index="727" value="11.00000"/>
 </variables>
</CPLEXSolution>
