<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="17855.8"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_6" index="5" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_11" index="10" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_0_20" index="19" value="1.00000"/>
  <variable name="x_0_21" index="20" value="1.00000"/>
  <variable name="x_0_22" index="21" value="1.00000"/>
  <variable name="x_1_17" index="39" value="1.00000"/>
  <variable name="x_2_8" index="53" value="1.00000"/>
  <variable name="x_3_0" index="69" value="1.00000"/>
  <variable name="x_4_5" index="96" value="1.00000"/>
  <variable name="x_5_0" index="115" value="1.00000"/>
  <variable name="x_6_13" index="150" value="1.00000"/>
  <variable name="x_7_23" index="183" value="1.00000"/>
  <variable name="x_8_0" index="184" value="1.00000"/>
  <variable name="x_9_0" index="207" value="1.00000"/>
  <variable name="x_10_0" index="230" value="1.00000"/>
  <variable name="x_11_0" index="253" value="1.00000"/>
  <variable name="x_12_0" index="276" value="1.00000"/>
  <variable name="x_13_19" index="317" value="1.00000"/>
  <variable name="x_14_0" index="322" value="1.00000"/>
  <variable name="x_15_0" index="345" value="1.00000"/>
  <variable name="x_16_0" index="368" value="1.00000"/>
  <variable name="x_17_10" index="401" value="1.00000"/>
  <variable name="x_18_16" index="430" value="1.00000"/>
  <variable name="x_19_0" index="437" value="1.00000"/>
  <variable name="x_20_12" index="472" value="1.00000"/>
  <variable name="x_21_9" index="492" value="1.00000"/>
  <variable name="x_22_1" index="507" value="1.00000"/>
  <variable name="x_23_0" index="529" value="1.00000"/>
  <variable name="u_1" index="552" value="16.00000"/>
  <variable name="u_2" index="553" value="25.00000"/>
  <variable name="u_3" index="554" value="50.00000"/>
  <variable name="u_4" index="555" value="30.00000"/>
  <variable name="u_5" index="556" value="56.00000"/>
  <variable name="u_6" index="557" value="11.00000"/>
  <variable name="u_7" index="558" value="14.00000"/>
  <variable name="u_8" index="559" value="55.00000"/>
  <variable name="u_9" index="560" value="55.00000"/>
  <variable name="u_10" index="561" value="56.00000"/>
  <variable name="u_11" index="562" value="53.00000"/>
  <variable name="u_12" index="563" value="47.00000"/>
  <variable name="u_13" index="564" value="18.00000"/>
  <variable name="u_14" index="565" value="56.00000"/>
  <variable name="u_15" index="566" value="38.00000"/>
  <variable name="u_16" index="567" value="55.00000"/>
  <variable name="u_17" index="568" value="48.00000"/>
  <variable name="u_18" index="569" value="12.00000"/>
  <variable name="u_19" index="570" value="55.00000"/>
  <variable name="u_20" index="571" value="27.00000"/>
  <variable name="u_21" index="572" value="40.00000"/>
  <variable name="u_22" index="573" value="9.00000"/>
  <variable name="u_23" index="574" value="46.00000"/>
 </variables>
</CPLEXSolution>
