<?xml version = "1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.23.222  -->
<CPLEXSolution version="1.0">
 <header
   problemName="CVRP"
   objectiveValue="17779.2"
  />
 <variables>
  <variable name="x_0_2" index="1" value="1.00000"/>
  <variable name="x_0_3" index="2" value="1.00000"/>
  <variable name="x_0_4" index="3" value="1.00000"/>
  <variable name="x_0_5" index="4" value="1.00000"/>
  <variable name="x_0_7" index="6" value="1.00000"/>
  <variable name="x_0_10" index="9" value="1.00000"/>
  <variable name="x_0_12" index="11" value="1.00000"/>
  <variable name="x_0_14" index="13" value="1.00000"/>
  <variable name="x_0_15" index="14" value="1.00000"/>
  <variable name="x_0_16" index="15" value="1.00000"/>
  <variable name="x_0_17" index="16" value="1.00000"/>
  <variable name="x_0_18" index="17" value="1.00000"/>
  <variable name="x_0_23" index="22" value="1.00000"/>
  <variable name="x_0_24" index="23" value="1.00000"/>
  <variable name="x_0_25" index="24" value="1.00000"/>
  <variable name="x_0_27" index="26" value="1.00000"/>
  <variable name="x_0_28" index="27" value="1.00000"/>
  <variable name="x_1_0" index="30" value="1.00000"/>
  <variable name="x_2_30" index="89" value="1.00000"/>
  <variable name="x_3_29" index="118" value="1.00000"/>
  <variable name="x_4_0" index="120" value="1.00000"/>
  <variable name="x_5_19" index="168" value="1.00000"/>
  <variable name="x_6_0" index="180" value="1.00000"/>
  <variable name="x_7_13" index="222" value="1.00000"/>
  <variable name="x_8_9" index="248" value="1.00000"/>
  <variable name="x_9_0" index="270" value="1.00000"/>
  <variable name="x_10_1" index="301" value="1.00000"/>
  <variable name="x_11_21" index="350" value="1.00000"/>
  <variable name="x_12_11" index="371" value="1.00000"/>
  <variable name="x_13_0" index="390" value="1.00000"/>
  <variable name="x_14_20" index="439" value="1.00000"/>
  <variable name="x_15_6" index="456" value="1.00000"/>
  <variable name="x_16_0" index="480" value="1.00000"/>
  <variable name="x_17_0" index="510" value="1.00000"/>
  <variable name="x_18_0" index="540" value="1.00000"/>
  <variable name="x_19_0" index="570" value="1.00000"/>
  <variable name="x_20_0" index="600" value="1.00000"/>
  <variable name="x_21_0" index="630" value="1.00000"/>
  <variable name="x_22_8" index="668" value="1.00000"/>
  <variable name="x_23_22" index="712" value="1.00000"/>
  <variable name="x_24_0" index="720" value="1.00000"/>
  <variable name="x_25_26" index="775" value="1.00000"/>
  <variable name="x_26_0" index="780" value="1.00000"/>
  <variable name="x_27_0" index="810" value="1.00000"/>
  <variable name="x_28_0" index="840" value="1.00000"/>
  <variable name="x_29_0" index="870" value="1.00000"/>
  <variable name="x_30_0" index="900" value="1.00000"/>
  <variable name="u_1" index="930" value="72.00000"/>
  <variable name="u_2" index="931" value="32.00000"/>
  <variable name="u_3" index="932" value="47.00000"/>
  <variable name="u_4" index="933" value="73.00000"/>
  <variable name="u_5" index="934" value="42.00000"/>
  <variable name="u_6" index="935" value="73.00000"/>
  <variable name="u_7" index="936" value="64.00000"/>
  <variable name="u_8" index="937" value="49.00000"/>
  <variable name="u_9" index="938" value="70.00000"/>
  <variable name="u_10" index="939" value="22.00000"/>
  <variable name="u_11" index="940" value="63.00000"/>
  <variable name="u_12" index="941" value="45.00000"/>
  <variable name="u_13" index="942" value="71.00000"/>
  <variable name="u_14" index="943" value="60.00000"/>
  <variable name="u_15" index="944" value="39.00000"/>
  <variable name="u_16" index="945" value="53.00000"/>
  <variable name="u_17" index="946" value="73.00000"/>
  <variable name="u_18" index="947" value="73.00000"/>
  <variable name="u_19" index="948" value="64.00000"/>
  <variable name="u_20" index="949" value="73.00000"/>
  <variable name="u_21" index="950" value="68.00000"/>
  <variable name="u_22" index="951" value="38.00000"/>
  <variable name="u_23" index="952" value="20.00000"/>
  <variable name="u_24" index="953" value="73.00000"/>
  <variable name="u_25" index="954" value="57.00000"/>
  <variable name="u_26" index="955" value="73.00000"/>
  <variable name="u_27" index="956" value="55.00000"/>
  <variable name="u_28" index="957" value="51.00000"/>
  <variable name="u_29" index="958" value="71.00000"/>
  <variable name="u_30" index="959" value="56.00000"/>
 </variables>
</CPLEXSolution>
